/* v14.2.2 QA — cargo securing quality / road shock / forced re-secure */
const CARGO_SECURE_MODES_V58={
 quick:{label:'快速固定',quality:.62,strapsPerAnchor:1,hoursPerAnchor:.05},
 standard:{label:'標準固定',quality:.82,strapsPerAnchor:1,hoursPerAnchor:.12},
 reinforced:{label:'加強固定',quality:.96,strapsPerAnchor:2,hoursPerAnchor:.22}
};
function ensureCargoSecureV58(){
 const t=ensureFieldTeamV43(),v=ensureVehicleStateV32();
 t.cargoSecure=t.cargoSecure||{schema:1,assetModes:{},assetQuality:{},pendingRefix:null,history:[]};
 t.cargoSecure.schema=1;t.cargoSecure.assetModes=t.cargoSecure.assetModes||{};t.cargoSecure.assetQuality=t.cargoSecure.assetQuality||{};t.cargoSecure.history=Array.isArray(t.cargoSecure.history)?t.cargoSecure.history:[];
 v.cargoRig=v.cargoRig||{schema:1,strapSets:state.logistics?.heavyReady?6:4,strapCondition:100,shockExposure:0,lastShock:null};
 v.cargoRig.schema=1;v.cargoRig.strapSets=Math.max(state.logistics?.heavyReady?6:4,Math.floor(+v.cargoRig.strapSets||0));v.cargoRig.strapCondition=clamp(+v.cargoRig.strapCondition||100,0,100);v.cargoRig.shockExposure=Math.max(0,+v.cargoRig.shockExposure||0);
 return t.cargoSecure
}
function secureModeV58(stop,asset){const s=ensureCargoSecureV58(),key=stop?.id||asset?.id;const id=s.assetModes[key]||'standard';return CARGO_SECURE_MODES_V58[id]||CARGO_SECURE_MODES_V58.standard}
function secureModeIdV58(stop,asset){const s=ensureCargoSecureV58(),key=stop?.id||asset?.id;return CARGO_SECURE_MODES_V58[s.assetModes[key]]?s.assetModes[key]:'standard'}
function secureEffectiveQualityV58(mode){const rig=ensureVehicleStateV32().cargoRig||ensureCargoSecureV58()&&ensureVehicleStateV32().cargoRig;return clamp(mode.quality*(.65+.35*clamp((rig?.strapCondition??100)/100,0,1)),.2,.99)}
function secureDemandV58(stop,asset){if(!asset)return {mode:CARGO_SECURE_MODES_V58.standard,straps:0,hours:0,quality:1};const sp=assetSpaceV54(asset.id),mode=secureModeV58(stop,asset),anchors=Math.max(1,sp.anchors||0);return {mode,straps:anchors*mode.strapsPerAnchor,hours:anchors*mode.hoursPerAnchor,quality:secureEffectiveQualityV58(mode),anchors}}
function setCargoSecureModeV58(stopId,modeId){const t=ensureFieldTeamV43(),it=ensureItineraryV27(),stop=it.stops.find(s=>String(s.id)===String(stopId));if(!stop||t.active)return toast('外勤開始後不能改固定方式');if(!CARGO_SECURE_MODES_V58[modeId])return;ensureCargoSecureV58().assetModes[stop.id]=modeId;renderMap();saveGame(false)}
function plannedSecureSummaryV58(){
 ensureCargoSecureV58();let used=0,hours=0,weakest=1,rows=[];
 for(const stop of ensureItineraryV27().stops){if(stop.action!=='asset')continue;const asset=assetAtStopV46(stop);if(!asset)continue;const d=secureDemandV58(stop,asset);used+=d.straps;hours+=d.hours;weakest=Math.min(weakest,d.quality);rows.push({stop,asset,...d,modeId:secureModeIdV58(stop,asset)})}
 const rig=ensureVehicleStateV32().cargoRig;return {used,available:rig.strapSets,hours,weakest,rows,ok:used<=rig.strapSets}
}
const _cargoExtraHoursV58=cargoExtraHoursV56;
cargoExtraHoursV56=function(stop){let h=_cargoExtraHoursV58(stop);if(stop?.action==='asset'&&ensureFieldTeamV43().useVehicle){const a=assetAtStopV46(stop);if(a){const c=ensureActualZoneStateV56?.();const loaded=!!c?.assets?.includes?.(a.id);if(!loaded)h+=secureDemandV58(stop,a).hours}}return h};
const _fieldTeamValidationV58=fieldTeamValidationV43;
fieldTeamValidationV43=function(e){const v=_fieldTeamValidationV58(e),s=plannedSecureSummaryV58(),issues=[...v.issues];if(ensureCargoSecureV58().pendingRefix)issues.push('貨物固定已鬆脫；必須先停車重新固定才能繼續行程');if(ensureFieldTeamV43().useVehicle&&s.used>s.available)issues.push(`大型設備固定需要 ${s.used} 組綁帶，但車上只有 ${s.available} 組`);return {...v,secure:s,ok:issues.length===0,issues:[...new Set(issues)]}}

const _loadAssetIntoDynamicCargoV58=loadAssetIntoDynamicCargoV52;
loadAssetIntoDynamicCargoV52=function(stop){const a=assetAtStopV46(stop),ok=_loadAssetIntoDynamicCargoV58(stop);if(ok&&a&&ensureFieldTeamV43().active&&ensureDynamicCargoV52().assets.includes(a.id)){const s=ensureCargoSecureV58(),d=secureDemandV58(stop,a);s.assetQuality[a.id]=d.quality;ensureDynamicCargoV52().assetZones[a.id]=cargoAssetZoneV56(stop,a);const st=state.assets?.[a.id];if(st&&st.condition==null)st.condition=100}return ok};

function cargoRoadRoughnessV58(route){const path=route?.path||[];if(path.length<2)return 0;let score=0,edges=0;for(let i=1;i<path.length;i++){const a=path[i-1],b=path[i],wa=roadWorldState(a,b),ka=roadIntelState(a,b);let r=((mapLoc(a)?.risk||0)+(mapLoc(b)?.risk||0))/8;if(wa?.status==='danger')r+=.45;if(wa?.status==='blocked')r+=.55;if(ka?.status==='danger')r+=.12;score+=r;edges++}return clamp(score/Math.max(1,edges),0,1.5)}
function weakestLoadedAssetV58(){const c=ensureDynamicCargoV52(),s=ensureCargoSecureV58();let best=null,score=Infinity;for(const id of c.assets){const a=assetDefs.find(x=>x.id===id);if(!a)continue;const q=clamp(s.assetQuality[id]??secureEffectiveQualityV58(CARGO_SECURE_MODES_V58.standard),.1,1),vulnerability=1+Math.max(0,a.weight-200)/900*.35,x=q/vulnerability;if(x<score){score=x;best={id,a,q,vulnerability}}}return best}
function shiftedZoneV58(zone){if(zone==='front')return 'mid';if(zone==='rear')return 'mid';if(zone==='mid')return Math.random()<0.5?'rear':'front';return zone}
function deterministicShiftZoneV58(zone,seed){if(zone==='front')return 'mid';if(zone==='rear')return 'mid';if(zone==='mid')return seed%2===0?'rear':'front';return zone}
function roadShockDoseV58(distance,route){const snap=dynamicCargoSnapshotV52(),rough=cargoRoadRoughnessV58(route),load=clamp(snap.used/Math.max(1,snap.capacity),0,1),offset=snap.balance?.offset||0,w=weakestLoadedAssetV58(),q=w?.q??1;return Math.max(0,distance)*(.20+rough*.80)*(.40+load*.80)*(1+offset*2)*(1+Math.max(0,.82-q)*1.2)}
function applyCargoRoadShockV58(distance,route,from,to){
 const t=ensureFieldTeamV43(),c=ensureDynamicCargoV52();if(!(t.active&&t.useVehicle&&c.assets.length&&distance>0))return {ok:true};const rig=ensureVehicleStateV32().cargoRig||ensureCargoSecureV58()&&ensureVehicleStateV32().cargoRig,dose=roadShockDoseV58(distance,route);rig.shockExposure+=dose;rig.strapCondition=clamp(rig.strapCondition-distance*.012,0,100);if(rig.shockExposure<3.0)return {ok:true,dose};rig.shockExposure=Math.max(0,rig.shockExposure-3.0);
 const rough=cargoRoadRoughnessV58(route),snap=dynamicCargoSnapshotV52(),weak=weakestLoadedAssetV58();if(!weak)return {ok:true,dose};const severity=clamp(.32+rough*.32+clamp(snap.used/Math.max(1,snap.capacity),0,1)*.18+(snap.balance?.offset||0)*.75+(1-weak.q)*.55,0,1.35),held=weak.q>=clamp(.68+severity*.16,.72,.92);rig.lastShock={day:state.day,from,to,assetId:weak.id,severity,held};
 if(held){const wear=1.2+severity*2.2;rig.strapCondition=clamp(rig.strapCondition-wear,0,100);ensureVehicleStateV32().condition=clamp((ensureVehicleStateV32().condition??100)-severity*.8,0,100);ensureCargoSecureV58().history.push({day:state.day,from,to,assetId:weak.id,held:true,severity});log(`${weak.a.name}遭遇路面衝擊，但固定保持；綁帶狀況下降。`,'major');return {ok:true,dose,shock:true,held:true}}
 const st=state.assets?.[weak.id];if(st){if(st.condition==null)st.condition=100;st.condition=clamp(st.condition-(4+severity*9),0,100)}ensureVehicleStateV32().condition=clamp((ensureVehicleStateV32().condition??100)-(2+severity*5),0,100);const oldZone=c.assetZones?.[weak.id]||ensureCargoLayoutV56().assetZones?.[weak.id]||'mid',seed=Math.round((state.day*17+distance*10+(st?.condition||0))),newZone=deterministicShiftZoneV58(oldZone,seed);c.assetZones=c.assetZones||{};c.assetZones[weak.id]=newZone;ensureCargoSecureV58().assetQuality[weak.id]=clamp(weak.q-.18-.10*severity,.2,.95);const after=dynamicCargoSnapshotV52(),hardStop=severity>.78||(after.balance?.offset||0)>.30||zoneCapacityIssuesV56(actualZoneLoadsV56(),fieldCargoGeometryV54().anchors).length>0;ensureCargoSecureV58().history.push({day:state.day,from,to,assetId:weak.id,held:false,severity,oldZone,newZone});
 if(hardStop){ensureCargoSecureV58().pendingRefix={assetId:weak.id,oldZone,newZone,from,to,severity,day:state.day};log(`${weak.a.name}在路面衝擊中移位，貨艙重心／局部載荷已不安全；必須停車重新固定。`,'bad');return {ok:false,reason:`${weak.a.name}固定鬆脫，必須停車重新固定`,dose,shock:true,held:false}}
 log(`${weak.a.name}在路面衝擊中發生位移並受損；目前仍可低速繼續，但固定品質下降。`,'bad');return {ok:true,dose,shock:true,held:false}
}
function resecureCargoV58(){const s=ensureCargoSecureV58(),p=s.pendingRefix,t=ensureFieldTeamV43();if(!p)return toast('目前沒有需要重新固定的貨物');if(!t.active||!t.useVehicle)return toast('重新固定只能在外勤工程車停車時進行');const a=assetDefs.find(x=>x.id===p.assetId),sp=assetSpaceV54(p.assetId),hours=.30+Math.min(.30,(a?.weight||0)/1200*.25),c=ensureDynamicCargoV52(),loads=actualZoneLoadsV56(),oldZone=p.oldZone;if(c.assetZones)c.assetZones[p.assetId]=oldZone;const test=actualZoneLoadsV56(),issues=zoneCapacityIssuesV56(test,fieldCargoGeometryV54().anchors);if(issues.length){if(c.assetZones)c.assetZones[p.assetId]=p.newZone;return toast(`無法恢復原固定位置：${issues[0]}`)}if(!sp)return toast('缺少設備固定資料');if(!spendWorldTimeV26(hours,{label:`重新固定${a?.name||p.assetId}`})){if(c.assetZones)c.assetZones[p.assetId]=p.newZone;return}const modeId=Object.entries(s.assetModes).find(([key])=>ensureItineraryV27().stops.find(st=>String(st.id)===String(key)&&assetAtStopV46(st)?.id===p.assetId))?.[1]||'standard',mode=CARGO_SECURE_MODES_V58[modeId]||CARGO_SECURE_MODES_V58.standard;s.assetQuality[p.assetId]=secureEffectiveQualityV58(mode);ensureVehicleStateV32().cargoRig.strapCondition=clamp(ensureVehicleStateV32().cargoRig.strapCondition-1.5,0,100);s.pendingRefix=null;s.history.push({day:state.day,assetId:p.assetId,refix:true,hours});log(`${a?.name||p.assetId}已重新固定，耗時 ${hours.toFixed(2)}h。`,'good');renderMap();saveGame(false)}

let cargoShockRouteContextV58=null;
const _runItineraryStepV58=runItineraryStepV27;
runItineraryStepV27=function(){const it=ensureItineraryV27(),t=ensureFieldTeamV43();if(t.active&&t.useVehicle&&ensureCargoSecureV58().pendingRefix)return pauseItineraryV27('貨物固定鬆脫，請先重新固定');const from=it.current||fieldTeamHomeV43(),stop=it.stops[it.index],to=stop?.location||fieldTeamHomeV43(),route=routeBetweenV27(from,to,it.routeMode);cargoShockRouteContextV58={from,to,route,used:false};try{return _runItineraryStepV58()}finally{cargoShockRouteContextV58=null}};
const _consumeVehicleDriveV58=consumeVehicleDriveV32;
consumeVehicleDriveV32=function(distance,hours,opts={}){const r=_consumeVehicleDriveV58(distance,hours,opts);if(!r?.ok)return r;const ctx=cargoShockRouteContextV58;if(ctx&&!ctx.used&&distance>0){ctx.used=true;const shock=applyCargoRoadShockV58(distance,ctx.route,ctx.from,ctx.to);if(!shock.ok){moveVehicleV32(ctx.to);ensureItineraryV27().current=ctx.to;syncFieldTeamLocationV43();return {ok:false,reason:shock.reason}}}return r};

function cargoSecureHtmlV58(){const t=ensureFieldTeamV43(),s=plannedSecureSummaryV58(),rig=ensureVehicleStateV32().cargoRig,locked=t.active,rows=s.rows.map(r=>`<div class="cargo-secure-row"><div><b>${r.asset.name}</b><small>${r.straps} 組綁帶 · 有效固定 ${(r.quality*100).toFixed(0)}% · +${r.hours.toFixed(2)}h</small></div><select data-secure-stop="${r.stop.id}" ${locked?'disabled':''}>${Object.entries(CARGO_SECURE_MODES_V58).map(([id,m])=>`<option value="${id}" ${r.modeId===id?'selected':''}>${m.label}</option>`).join('')}</select></div>`).join('')||'<p class="muted">目前行程沒有需要大型固定的設備。</p>';const p=ensureCargoSecureV58().pendingRefix,last=(ensureCargoSecureV58().history||[]).slice(-3).reverse();return `<section class="cargo-secure-box ${p?'blocked':''}"><div class="source-load-head"><div><span>CARGO SECURING</span><h3>大型設備固定／路面衝擊</h3></div><b>${s.used} / ${s.available} 組綁帶</b></div><div class="cargo-secure-metrics"><span>綁帶狀況 <b>${rig.strapCondition.toFixed(0)}%</b></span><span>預估固定工時 <b>${s.hours.toFixed(2)}h</b></span><span>最弱固定 <b>${(s.weakest*100).toFixed(0)}%</b></span><span>衝擊累積 <b>${rig.shockExposure.toFixed(2)}</b></span></div>${rows}${!s.ok?'<div class="field-team-issues"><p>綁帶組數不足，請降低固定模式或減少同時回收的大型設備。</p></div>':''}${p?`<div class="cargo-refix"><b>${assetDefs.find(a=>a.id===p.assetId)?.name||p.assetId} 已移位</b><span>${CARGO_ZONE_LABEL_V56[p.oldZone]||p.oldZone} → ${CARGO_ZONE_LABEL_V56[p.newZone]||p.newZone}</span><button id="cargoResecure">停車重新固定</button></div>`:''}${last.length?`<div class="cargo-shock-history">${last.map(x=>`<small>Day ${x.day} · ${x.refix?'重新固定':x.held?'固定保持':'貨物移位'} · ${assetDefs.find(a=>a.id===x.assetId)?.name||x.assetId}</small>`).join('')}</div>`:''}</section>`}
const _subtaskPlannerHtmlV58=subtaskPlannerHtmlV46;
subtaskPlannerHtmlV46=function(){const html=_subtaskPlannerHtmlV58(),box=cargoSecureHtmlV58();return html.replace('<div class="parallel-stop-list">',box+'<div class="parallel-stop-list">')};
const _bindItineraryPlannerV58=bindItineraryPlannerV27;
bindItineraryPlannerV27=function(){_bindItineraryPlannerV58();document.querySelectorAll('[data-secure-stop]').forEach(x=>x.onchange=()=>setCargoSecureModeV58(x.dataset.secureStop,x.value));if($('cargoResecure'))$('cargoResecure').onclick=resecureCargoV58};
ensureCargoSecureV58();
