function openResearch(){$('researchList').innerHTML=researchDefs.map(r=>{const done=state.research[r.id],can=r.req(),enough=state.resources.data>=r.cost;return `<div class="card"><h3>${r.name}</h3><p>${r.desc}</p><p>需要研究資料：${r.cost}（持有 ${state.resources.data}）</p><p class="status">${done?'已完成':!can?'前置條件不足':enough?'可研究':'資料不足'}</p><button data-research="${r.id}" ${done||!can||!enough?'disabled':''}>${done?'已完成':'研究'}</button></div>`}).join('');$('researchDialog').showModal();document.querySelectorAll('[data-research]').forEach(b=>b.onclick=()=>doResearch(b.dataset.research))}
function doResearch(id){const r=researchDefs.find(x=>x.id===id);if(!r||state.research[id]||!r.req()||state.resources.data<r.cost)return;state.resources.data-=r.cost;state.research[id]=true;log(`研究完成：${r.name}`,'major');$('researchDialog').close();render()}
function openCraft(){$('craftList').innerHTML=craftDefs.map(c=>{const ok=c.cond(),enough=hasCost(c.cost);return `<div class="card"><h3>${c.name}</h3><p>${c.desc}</p><p>需求：${Object.entries(c.cost).map(([k,v])=>`${RES_LABELS[k]||k} ${v}（有 ${Math.floor(state.resources[k]||0)}）`).join('、')}</p><p class="status">${ok?(enough?'可施工':'材料不足'):'目前條件未達成'}</p><button data-craft="${c.id}" ${!ok||!enough?'disabled':''}>施工</button></div>`}).join('');$('craftDialog').showModal();document.querySelectorAll('[data-craft]').forEach(b=>b.onclick=()=>craft(b.dataset.craft))}
function craft(id){const c=craftDefs.find(x=>x.id===id);if(!c||!c.cond()||!hasCost(c.cost))return;pay(c.cost);c.effect();log(`完成工程：${c.name}`,'good');$('craftDialog').close();render();checkState()}
function openInventory(){const assets=[['推車',state.gear.cart?'1 台':'—'],['工程車',state.gear.vehicle?`1 台 · 載重 ${transportCapacityFor('vehicle')}kg`:'—'],['遠征工具箱',state.gear.toolkit?'1 組':'—'],['200L 儲水架',state.gear.waterTank?'已建':'—'],['太陽能陣列',state.gear.solar?'已建':'—'],['主動冷卻背包',state.gear.coolingPack?'1 套':'—'],['外部冷站',state.coldStations.length+' 座'],['中央通風站',state.base.core?'核心完成':state.base.ventilation?`階段 ${state.base.ventilation}`:'未啟動']];$('inventoryContent').innerHTML=`<div class="asset-grid"><div class="asset-box"><h3>小型庫存</h3>${Object.entries(state.resources).map(([k,v])=>`<div class="trade-item"><span>${RES_LABELS[k]||k}</span><b>${Math.floor(v)}</b></div>`).join('')}</div><div class="asset-box"><h3>設備／大型資產</h3>${assets.map(a=>`<div class="trade-item"><span>${a[0]}</span><b>${a[1]}</b></div>`).join('')}</div></div><h3>大型資產位置</h3>${assetDefs.filter(a=>state.assets[a.id].discovered||state.assets[a.id].transported).map(a=>`<div class="trade-item"><span>${a.name}</span><b>${state.assets[a.id].transported?'中央站／基地':(locations.find(l=>l.id===state.assets[a.id].location)?.name||state.settlements[state.assets[a.id].location]?.name||'未知')} · ${ownerLabel(state.assets[a.id].owner)}</b></div>`).join('')||'<p class="muted">尚未發現大型設備。</p>'}<p class="muted">大型資產必須實際搬運，找到不代表已經擁有。</p>`;$('inventoryDialog').showModal()}

function healthClass(h){return h>=75?'health-good':h>=45?'health-warn':'health-bad'}
function openSettlements(){const npcHtml=Object.values(state.npcs).map(n=>`<div class="settlement"><div class="settlement-head"><h3>${n.name} · ${n.role}</h3><b class="${n.alive?'health-good':'health-bad'}">${n.alive?'存活':'死亡'}</b></div><p>位置：${locations.find(l=>l.id===n.location)?.name||'未知'}｜信任 ${n.trust}｜目前需求 ${normalizeNeed(n)}</p></div>`).join('');const sHtml=Object.values(state.settlements).map(s=>`<div class="settlement"><div class="settlement-head"><h3>${s.name}</h3><b>${s.population} 人</b></div><p>位置：${locations.find(l=>l.id===s.location)?.name||s.location}｜水 ${Math.floor(s.water)}L｜食物 ${Math.floor(s.food)}｜狀態 <span class="${healthClass(s.health)}">${s.status}</span></p><div class="progressbar ${s.health<45?'bad':s.health<75?'warn':''}"><i style="width:${clamp(s.health,0,100)}%"></i></div></div>`).join('');$('settlementContent').innerHTML=`<h3>具名 NPC</h3>${npcHtml}<h3>聚落</h3>${sHtml}`;$('settlementDialog').showModal()}
function openIntel(){
 const items=Object.entries(state.intel).sort((a,b)=>(b[1].verifiedDay??b[1].day)-(a[1].verifiedDay??a[1].day));
 const rumors=state.rumors.filter(r=>!r.shared).slice(-5).reverse();
 const notes=(state.mapNotes||[]).slice().reverse();
 const roadRows=MAP_ROUTES.map(([a,b])=>{const key=roadKey(a,b),i=state.roadIntel[key];if(!i)return null;const age=roadIntelAge(i),conf=roadIntelConfidence(i),status=i.status==='blocked'?'封鎖':i.status==='danger'?'危險':i.status==='repaired'?'已修復':'暢通';return `<div class="intel-row road-intel ${conf<45?'stale':''}"><strong>${roadName(key)}</strong><span>${status}｜來源：${i.source||'未知'}｜可信 ${conf}%</span><em class="intel-age">${age?age+' 天前':'今日'}</em>${i.status==='blocked'?`<button class="mini" data-repairroad="${key}" ${state.resources.parts<6?'disabled':''}>派隊清障 · 6 零件</button>`:''}</div>`}).filter(Boolean).join('')||'<p class="muted">尚未取得道路狀態情報。親自遠征會驗證走過的路段。</p>';
 $('intelContent').innerHTML=`<div class="intel-console"><section><h3>地點情報</h3><div class="intel-list">${items.length?items.map(([id,i])=>{const l=locations.find(x=>x.id===id),age=state.day-(i.verifiedDay??i.day),c=clamp(Math.round((i.confidence??75)-age*8),10,100);return `<div class="intel-row ${c<45?'stale':''}"><strong>${l?.name||id}</strong><span>${i.summary}｜來源：${i.source||'未知'}｜可信 ${c}%</span><em class="intel-age">${age?age+' 天前':'今日'}</em></div>`}).join(''):'<p class="muted">尚未取得城市情報。</p>'}</div></section><section><h3>道路情報</h3><div class="intel-list">${roadRows}</div></section></div><h3>玩家地圖標記</h3><div class="note-editor"><select id="noteLocation">${locations.map(l=>`<option value="${l.id}">${l.name}</option>`).join('')}</select><select id="noteType"><option value="todo">待辦</option><option value="water">水源</option><option value="asset">設備</option><option value="danger">危險</option><option value="route">路線</option></select><input id="noteText" maxlength="64" placeholder="例如：這裡還有一個大型水桶"><button id="addMapNote">加入標記</button></div><div class="intel-list">${notes.length?notes.map(n=>`<div class="intel-row"><strong>${noteTypeLabel(n.type)} · ${mapLoc(n.location)?.name||n.location}</strong><span>${n.text}</span><em class="intel-age">Day ${n.day}</em><button class="mini secondary" data-delnote="${n.id}">刪除</button></div>`).join(''):'<p class="muted">尚未建立玩家標記。</p>'}</div><h3>未取得的傳聞</h3><p class="muted">你知道城市裡有人掌握 ${rumors.length} 條尚未交換給你的情報。傳聞可能在你取得以前就已經過期。</p>`;
 $('intelDialog').showModal();
 $('addMapNote').onclick=()=>{const txt=$('noteText').value.trim();if(!txt)return toast('先輸入標記內容');state.mapNotes.push({id:state.intelSeq++,location:$('noteLocation').value,type:$('noteType').value,text:txt,day:state.day});log(`你在地圖標記：${mapLoc($('noteLocation').value).name}｜${txt}`);openIntel();renderMap();saveGame(false)};
 document.querySelectorAll('[data-delnote]').forEach(b=>b.onclick=()=>{state.mapNotes=state.mapNotes.filter(n=>String(n.id)!==b.dataset.delnote);openIntel();renderMap();saveGame(false)});
 document.querySelectorAll('[data-repairroad]').forEach(b=>b.onclick=()=>{const key=b.dataset.repairroad;if(state.resources.parts<6)return toast('零件不足');const [a,c]=roadEnds(key);state.resources.parts-=6;state.roadWorld[key]={status:'open',changedDay:state.day};state.roadIntel[key]={status:'repaired',source:'中央站清障隊',day:state.day,verifiedDay:state.day,confidence:100};log(`清障隊修復道路：${roadName(key)}。`,'good');openIntel();render();saveGame(false)});
}
