function openLocation(id){preloadScene(id);const loc=locations.find(x=>x.id===id),lc=state.locations[id];$('locTitle').textContent=loc.name;$('locDesc').innerHTML=`<div class="location-hero"><div class="location-scene${sceneClass(id)}"><img class="scene-base" src="${locationArt(id)}" alt="${loc.name}" decoding="async">${sceneOverlayHtml(id)}${districtHistoryHtml(id)}<span class="scene-quality">${sceneBadge(id)} · ${sceneMode().toUpperCase()}</span></div><div class="location-hero-copy"><p>${loc.desc}</p><div class="tag-row">${locationTags(id).map(t=>`<span class="tag">${t}</span>`).join('')}</div>${sceneStatusHtml(id)}</div></div>`;const intel=intelLabel(id);$('locMeta').innerHTML=`<div class="meta"><span>搜索耗時</span>${timeCostFor(loc)} 小時</div><div class="meta"><span>單趟載重</span>${cargoCapacityKg()} kg</div><div class="meta"><span>車輛燃料</span>${state.gear.vehicle?travelFuelCost(loc)+' L':'—'}</div><div class="meta"><span>永晝耗電</span>${state.day>=30?coolingCost(loc)+' kWh':'—'}</div><div class="meta"><span>情報</span>${intel||'無'}</div>`;$('locStock').innerHTML=lc.searched?stockChips(lc.remaining):(state.intel[id]?`<span class="muted">${state.intel[id].summary}；實際數量仍需搜索確認。</span>`:'<span class="muted">尚未掌握這裡的庫存。</span>');const npc=Object.entries(state.npcs).find(([,n])=>n.alive&&n.location===id);let a=[];if(id!=='base'){a.push('<button id="searchLoc">快速搜索</button>');a.push('<button id="planLoc" class="secondary">規劃遠征</button>');}if(npc)a.push('<button id="tradeLoc" class="secondary">交易／搶奪</button>');if(loc.special==='vent')a.push('<button id="openCraftFromLoc" class="secondary">中央站工程</button>');$('locActions').innerHTML=a.join('');$('locationDialog').showModal();if($('searchLoc'))$('searchLoc').onclick=()=>searchLocation(loc);if($('planLoc'))$('planLoc').onclick=()=>{$('locationDialog').close();openActionCenter(id)};if($('tradeLoc'))$('tradeLoc').onclick=()=>openTrade(npc[0]);if($('openCraftFromLoc'))$('openCraftFromLoc').onclick=()=>{$('locationDialog').close();openCraft()}}
function searchLocation(loc){
 if(!isSafeSearch(loc))return toast(state.day<30?'白晝無法安全搜索':'永晝中缺少主動冷卻');
 const tc=timeCostFor(loc);if(state.day<30&&state.hoursLeft<tc)return toast('剩餘時間不足');
 const cc=state.day>=30?coolingCost(loc):0,fc=travelFuelCost(loc);
 if(state.gear.vehicle&&state.resources.fuel<fc)return toast('車輛燃料不足');
 if(state.day>=30&&state.resources.battery<cc)return toast('冷卻與交通電力不足');
 if(state.day<30)state.hoursLeft-=tc;else state.resources.battery-=cc;if(state.gear.vehicle)state.resources.fuel-=fc;
 let cap=cargoCapacityKg(),used=0,gain={},rem=state.locations[loc.id].remaining;
 for(const k of RES_ORDER){const av=rem[k]||0;if(av<=0||cap-used<=.05)continue;const w=RES_WEIGHT[k]||1;const maxByWeight=Math.floor((cap-used)/w);if(maxByWeight<=0)continue;const take=Math.min(av,maxByWeight);rem[k]-=take;state.resources[k]+=take;gain[k]=take;used+=take*w}
 tutorialWaterGain(gain);state.locations[loc.id].searched=true;state.intel[loc.id]={day:state.day,verifiedDay:state.day,summary:summarizeRemaining(rem),source:'親自搜索',confidence:100};
 discoverAssetsAt(loc.id);
 if(loc.special==='cart'&&!state.gear.cart){state.gear.cart=true;log('你在五金行整理出一台可用推車，單趟載重提升到 80kg。','good')}
 if(loc.special==='vehicle'&&!state.gear.vehicle&&state.resources.fuel>=2){state.gear.vehicle=true;state.resources.fuel-=2;log('陳技師協助你修復了一台工程車，單趟載重提升到 700kg。','good')}
 if(loc.special==='coreInfo'&&!state.knownCore&&state.resources.data>=4){state.knownCore=true;log('研究資料確認：冷源核心仍在地下熱工實驗艙。','major')}
 if(loc.special==='solar'&&state.resources.data>=2)log('你取得太陽能場的逆變與配電資料。','good');
 log(`${loc.name} 搜索：${Object.entries(gain).map(([k,v])=>`${RES_LABELS[k]||k}+${v}`).join('、')||'沒有實質收穫'}｜裝載 ${Math.round(used)} / ${cap} kg`);
 $('locationDialog').close();render();checkState()
}
function summarizeRemaining(rem){const pairs=Object.entries(rem).filter(([,v])=>v>0).sort((a,b)=>b[1]-a[1]).slice(0,2);if(!pairs.length)return '物資可能已接近耗盡';return pairs.map(([k,v])=>`${RES_LABELS[k]||k} ${v>20?'很多':v>8?'一些':'少量'}`).join('、')}

function tradeOfferFor(n){n.need=normalizeNeed(n);const offers=[];if(n.need==='水'&&n.stock.water<6){if(n.stock.medicine>=2)offers.push({label:'4L 水換 2 藥品',give:{water:4},take:{medicine:2}});else if(n.stock.parts>=2)offers.push({label:'4L 水換 2 零件',give:{water:4},take:{parts:2}})}
 if(n.need==='食物'&&n.stock.food<4&&n.stock.battery>=1)offers.push({label:'3 食物換 1 kWh 電池',give:{food:3},take:{battery:1}});
 if(n.need==='藥品'&&n.stock.medicine<2&&n.stock.parts>=2)offers.push({label:'1 藥品換 2 零件',give:{medicine:1},take:{parts:2}});
 if(n.need==='電池'&&n.stock.battery<1&&n.stock.water>=5)offers.push({label:'2 kWh 電池換 5L 水',give:{battery:2},take:{water:5}});
 if(n.need==='冷媒'&&n.stock.coolant<3&&n.stock.parts>=3)offers.push({label:'2 冷媒換 3 零件',give:{coolant:2},take:{parts:3}});
 if(!offers.length&&n.stock.water>=6)offers.push({label:'4 食物換 6L 水',give:{food:4},take:{water:6}});return offers.slice(0,2)}
function canGive(obj){return Object.entries(obj).every(([k,v])=>(state.resources[k]||0)>=v)}
function npcHas(n,obj){return Object.entries(obj).every(([k,v])=>(n.stock[k]||0)>=v)}
function applyTrade(n,o){if(!canGive(o.give)||!npcHas(n,o.take))return toast('交易條件不足');Object.entries(o.give).forEach(([k,v])=>{state.resources[k]-=v;n.stock[k]=(n.stock[k]||0)+v});Object.entries(o.take).forEach(([k,v])=>{n.stock[k]-=v;state.resources[k]+=v});n.trust+=2;state.base.trust++;log(`與${n.name}完成交易：${o.label}。`,'good');closeTrade()}
function openTrade(id){const n=state.npcs[id];const offers=tradeOfferFor(n);$('tradeTitle').textContent=`${n.name}｜${n.role}`;$('tradeContent').innerHTML=`<p>目前最缺：<b>${n.need}</b>　信任：<b>${n.trust}</b>。NPC 的需求會依實際庫存每天改變。</p><div class="trade-grid"><div class="trade-side"><h3>${n.name} 庫存</h3>${Object.entries(n.stock).map(([k,v])=>`<div class="trade-item"><span>${RES_LABELS[k]||k}</span><b>${Math.floor(v)}</b></div>`).join('')}</div><div class="trade-side"><h3>你的庫存</h3>${Object.entries(state.resources).map(([k,v])=>`<div class="trade-item"><span>${RES_LABELS[k]||k}</span><b>${Math.floor(v)}</b></div>`).join('')}</div></div><div class="trade-actions">${offers.map((o,i)=>`<button data-offer="${i}">${o.label}</button>`).join('')}<button id="helpNpc" class="secondary">贈送 4L 水</button><button id="askIntel" class="secondary">交換情報</button><button id="robNpc" class="danger-btn">直接搶奪</button></div>`;$('tradeDialog').showModal();document.querySelectorAll('[data-offer]').forEach(b=>b.onclick=()=>applyTrade(n,offers[+b.dataset.offer]));$('helpNpc').onclick=()=>{if(state.resources.water<4)return toast('水不足');state.resources.water-=4;n.stock.water+=4;n.trust+=3;state.base.trust+=2;log(`你把 4L 水交給${n.name}。`,'good');closeTrade()};$('askIntel').onclick=()=>{const r=state.rumors.find(x=>!x.shared&&x.source===n.name)||state.rumors.find(x=>!x.shared);if(!r)return toast('他目前沒有新的可靠情報');if(state.resources.food<1)return toast('至少準備 1 單位食物交換情報');state.resources.food-=1;r.shared=true;state.intel[r.location]={day:r.day,verifiedDay:r.day,summary:r.summary,source:r.source,confidence:68};n.trust++;log(`${n.name}告訴你：${locations.find(l=>l.id===r.location).name}可能有${r.summary}。`,'good');closeTrade()};$('robNpc').onclick=()=>{let s=0;for(const k of ['water','food','battery','medicine','parts','coolant']){const t=Math.min(n.stock[k]||0,3);n.stock[k]-=t;state.resources[k]+=t;s+=t}n.trust-=8;state.base.trust-=4;log(`你直接搬走${n.name}的物資（${s} 單位）。之後他更可能隱藏庫存與拒絕合作。`,'bad');closeTrade()}}
function closeTrade(){$('tradeDialog').close();render()}

