// v15.4 Batch 7 — local / short-chain NPC wave; encounter-gated and location-bound.
(function(){
 const LOCAL_NPCS_V130={
  'npc-hong-ayi':{name:'洪阿姨',role:'住戶',home:'homes',priority:'確認鄰居是否還在',topics:['現在狀況','附近的人','最近看到什麼']},
  'npc-xiao-ke':{name:'小柯',role:'受傷住戶',home:'school',priority:'先處理傷勢',topics:['現在狀況','傷勢','需要什麼']},
  'npc-wei-shifu':{name:'魏師傅',role:'退休水電工',home:'hardware',priority:'確認附近水路',topics:['現在狀況','以前的工作','這裡的管線']},
  'npc-anqi':{name:'安琪',role:'失散家屬',home:'store',priority:'找失散的家人',topics:['現在狀況','在找誰','最後看到的地方']},
  'npc-lao-he':{name:'老何',role:'拾荒者',home:'warehouse',priority:'保住手上的東西',topics:['現在狀況','手上的東西','最近去過哪裡']},
  'npc-mei':{name:'阿梅',role:'照護者',home:'clinic',priority:'照顧身邊的人',topics:['現在狀況','照護對象','目前需要']},
  'npc-haozi':{name:'浩子',role:'臨時商販',home:'subway',priority:'找能交換的東西',topics:['現在狀況','交換','最近聽到什麼']},
  'npc-yu':{name:'阿宇',role:'獨行倖存者',home:'industrial',priority:'找下一個安全落腳處',topics:['現在狀況','走過的地方','接下來打算']}
 };
 function makeLocalNpcV130(id,d){return{id,name:d.name,role:d.role,location:d.home,home:d.home,priority:d.priority,alive:true,encountered:false,trust:0,talked:[],lastBody:''}}
 function ensureLocalNpcV130(s=state){s.localNpcV130=s.localNpcV130&&typeof s.localNpcV130==='object'?s.localNpcV130:{};const ls=s.localNpcV130;ls.people=ls.people&&typeof ls.people==='object'?ls.people:{};ls.knownIds=Array.isArray(ls.knownIds)?ls.knownIds:[];for(const[id,d]of Object.entries(LOCAL_NPCS_V130))if(!ls.people[id])ls.people[id]=makeLocalNpcV130(id,d);return ls}
 function localNpcV130(id,s=state){return ensureLocalNpcV130(s).people[id]||null}
 function currentLocV130(s=state){return s.explorationV113?.current||(typeof ensureExplorationV113==='function'?ensureExplorationV113(s).current:'base')}
 function observedV130(loc,s=state){return s.explorationV118?.observed?.[loc]===true}
 function presentLocalV130(loc=currentLocV130(),s=state){return Object.values(ensureLocalNpcV130(s).people).filter(n=>n.alive&&n.location===loc)}
 function encounterLocalV130(id,s=state){const n=localNpcV130(id,s);if(!n||!n.alive)return null;n.encountered=true;const ls=ensureLocalNpcV130(s);if(!ls.knownIds.includes(id))ls.knownIds.push(id);return n}
 function canTalkLocalV130(id,s=state){const n=localNpcV130(id,s),loc=currentLocV130(s);return !!(n&&n.alive&&n.encountered&&n.location===loc&&observedV130(loc,s))}
 function localTopicsV130(id){const d=LOCAL_NPCS_V130[id];return(d?.topics||[]).map((label,i)=>({id:`${id}-l${String(i+1).padStart(2,'0')}`,label,index:i}))}
 function availableLocalTopicsV130(id,s=state){const n=localNpcV130(id,s),all=localTopicsV130(id);if(!n)return[];return all.slice(0,Math.min(all.length,2+n.talked.length))}
 function localBodyV130(n,index){if(index===0)return`${n.name}目前最在意的是「${n.priority}」。`;if(index===1)return`「我只說自己確定的。現在先把${n.priority}這件事處理好。」`;return'「其他消息我沒有親眼確認；如果只是聽來的，我不會當成事實。」'}
 function talkLocalV130(id,topicId,s=state){if(!canTalkLocalV130(id,s))return{ok:false,reason:'對方現在不在這裡'};const n=localNpcV130(id,s),topic=localTopicsV130(id).find(t=>t.id===topicId);if(!topic||!availableLocalTopicsV130(id,s).some(t=>t.id===topicId))return{ok:false,reason:'現在還談不到這件事'};const first=!n.talked.includes(topicId);if(first){n.talked.push(topicId);n.trust=Math.min(3,n.trust+1)}n.lastBody=localBodyV130(n,topic.index);return{ok:true,first,trust:n.trust,body:n.lastBody}}
 function renderLocalNpcV130(){if(!state.flags?.hardFogOpeningV112)return;const map=document.getElementById('map');if(!map)return;map.querySelector('.local-presence-v130')?.remove();const loc=currentLocV130();if(!observedV130(loc))return;const present=presentLocalV130(loc);if(!present.length)return;for(const n of present)encounterLocalV130(n.id);const panel=document.createElement('section');panel.className='local-presence-v130';panel.setAttribute('aria-label','你在這裡遇見的人');for(const n of present){const card=document.createElement('article');card.className='local-card-v130';card.dataset.localNpcV130=n.id;const b=document.createElement('b');b.textContent=n.name;const small=document.createElement('small');small.textContent=`${n.role} · ${n.trust>=2?'熟悉':'陌生'}`;card.append(b,small);if(n.lastBody){const p=document.createElement('p');p.textContent=n.lastBody;card.appendChild(p)}const topics=document.createElement('div');topics.className='local-topics-v130';for(const t of availableLocalTopicsV130(n.id)){const btn=document.createElement('button');btn.type='button';btn.textContent=t.label;btn.dataset.talkLocalV130=`${n.id}|${t.id}`;topics.appendChild(btn)}card.appendChild(topics);panel.appendChild(card)}panel.querySelectorAll('[data-talk-local-v130]').forEach(btn=>btn.onclick=()=>{const[id,tid]=btn.dataset.talkLocalV130.split('|'),r=talkLocalV130(id,tid);if(!r.ok){if(typeof toast==='function')toast(r.reason);return}renderMap()});map.appendChild(panel)}
 function stylesV130(){if(document.getElementById('localNpcStylesV130'))return;const st=document.createElement('style');st.id='localNpcStylesV130';st.textContent='.local-presence-v130{position:absolute;left:18px;top:18px;z-index:14;width:min(330px,40%);display:grid;gap:8px;padding:11px;border:1px solid rgba(205,195,180,.18);border-radius:11px;background:rgba(18,16,14,.95)}.local-card-v130{display:grid;gap:7px;padding:9px;border:1px solid rgba(205,195,180,.12);border-radius:8px}.local-card-v130 small{opacity:.7;font-size:.75rem}.local-card-v130 p{margin:0;font-size:.8rem;line-height:1.42}.local-topics-v130{display:flex;flex-wrap:wrap;gap:6px}.local-topics-v130 button{font-size:.75rem}@media(max-width:900px){.local-presence-v130{position:relative;left:auto;top:auto;width:auto;margin:12px}}';document.head.appendChild(st)}
 const prevMakeStateV130=makeState;makeState=function(){const s=prevMakeStateV130();ensureLocalNpcV130(s);return s};ensureLocalNpcV130(state);
 const prevRenderMapV130=renderMap;renderMap=function(){const out=prevRenderMapV130();stylesV130();queueMicrotask(renderLocalNpcV130);return out};
 const prevRenderV130=render;render=function(){const out=prevRenderV130();stylesV130();queueMicrotask(renderLocalNpcV130);return out};
 stylesV130();window.LOCAL_NPCS_V130=LOCAL_NPCS_V130;window.ensureLocalNpcV130=ensureLocalNpcV130;window.localNpcV130=localNpcV130;window.presentLocalV130=presentLocalV130;window.encounterLocalV130=encounterLocalV130;window.canTalkLocalV130=canTalkLocalV130;window.availableLocalTopicsV130=availableLocalTopicsV130;window.talkLocalV130=talkLocalV130;window.renderLocalNpcV130=renderLocalNpcV130;
})();