/* v14.2.2 QA — cargo bay layout / access depth / load order / center-of-mass effects */
const CARGO_ZONE_ORDER_V56=['rear','mid','front'];
const CARGO_ZONE_LABEL_V56={rear:'後艙／門側',mid:'中艙',front:'前艙／深處'};
function cargoZoneDefsV56(){
 const t=ensureFieldTeamV43();
 if(!(t.useVehicle&&state.gear?.vehicle))return {carry:{label:'人力攜行',pos:.5,volumeL:fieldCargoGeometryV54().volumeL,localKg:fieldCargoCapacityV50(),localAnchors:0}};
 const heavy=!!state.logistics?.heavyReady;
 return heavy?{
  rear:{label:CARGO_ZONE_LABEL_V56.rear,pos:.78,volumeL:1000,localKg:520,localAnchors:1},
  mid:{label:CARGO_ZONE_LABEL_V56.mid,pos:.50,volumeL:1400,localKg:680,localAnchors:2},
  front:{label:CARGO_ZONE_LABEL_V56.front,pos:.24,volumeL:1200,localKg:560,localAnchors:1}
 }:{
  rear:{label:CARGO_ZONE_LABEL_V56.rear,pos:.78,volumeL:700,localKg:320,localAnchors:1},
  mid:{label:CARGO_ZONE_LABEL_V56.mid,pos:.50,volumeL:1050,localKg:440,localAnchors:2},
  front:{label:CARGO_ZONE_LABEL_V56.front,pos:.24,volumeL:850,localKg:360,localAnchors:1}
 }
}
function ensureCargoLayoutV56(){
 const t=ensureFieldTeamV43();t.cargoLayout=t.cargoLayout||{schema:1,policy:{toolkit:'rear',medkit:'rear',spares:'mid',portable:'rear',recovery:'rear'},assetZones:{}};t.cargoLayout.schema=1;t.cargoLayout.policy=t.cargoLayout.policy||{};t.cargoLayout.assetZones=t.cargoLayout.assetZones||{};
 const zones=cargoZoneDefsV56(),valid=new Set(Object.keys(zones));const fallback=valid.has('rear')?'rear':[...valid][0];for(const k of ['toolkit','medkit','spares','portable','recovery'])if(!valid.has(t.cargoLayout.policy[k]))t.cargoLayout.policy[k]=fallback;
 for(const [k,z] of Object.entries(t.cargoLayout.assetZones))if(!valid.has(z))delete t.cargoLayout.assetZones[k];
 const c=ensureDynamicCargoV52();c.resourceZones=c.resourceZones||{};c.assetZones=c.assetZones||{};
 return t.cargoLayout
}
function cargoZoneForFixedV56(kind){const l=ensureCargoLayoutV56(),zones=cargoZoneDefsV56();return zones[l.policy[kind]]?l.policy[kind]:Object.keys(zones)[0]}
function cargoAssetZoneV56(stop,asset){const l=ensureCargoLayoutV56(),zones=cargoZoneDefsV56(),key=stop?.id||asset?.id;let z=l.assetZones[key];if(zones[z])return z;const entries=Object.keys(zones),sp=asset?assetSpaceV54(asset.id):{anchors:0};z=entries.find(id=>(zones[id].localAnchors||0)>=sp.anchors&&id!=='rear')||entries.find(id=>(zones[id].localAnchors||0)>=sp.anchors)||entries[0];l.assetZones[key]=z;return z}
function setCargoPolicyV56(kind,zone){const t=ensureFieldTeamV43(),zones=cargoZoneDefsV56();if(t.active)return toast('外勤開始後不能重排貨艙');if(!zones[zone])return;t.cargoLayout=t.cargoLayout||{};ensureCargoLayoutV56().policy[kind]=zone;renderMap();saveGame(false)}
function setCargoAssetZoneV56(stopId,zone){const t=ensureFieldTeamV43(),zones=cargoZoneDefsV56();if(t.active)return toast('外勤開始後不能改大型設備固定位置');if(!zones[zone])return;ensureCargoLayoutV56().assetZones[stopId]=zone;renderMap();saveGame(false)}
function emptyZoneLoadsV56(){const out={};for(const [id,d] of Object.entries(cargoZoneDefsV56()))out[id]={id,label:d.label,pos:d.pos,kg:0,volumeL:0,anchors:0,items:[],dynamicVolumeL:0};return out}
function addZoneLoadV56(loads,zone,item){const z=loads[zone]||loads[Object.keys(loads)[0]];z.kg+=Math.max(0,+item.kg||0);z.volumeL+=Math.max(0,+item.volumeL||0);z.anchors+=Math.max(0,+item.anchors||0);if(item.dynamic)z.dynamicVolumeL+=Math.max(0,+item.volumeL||0);z.items.push(item);return z}
function fixedZoneLoadsV56(){
 const loads=emptyZoneLoadsV56(),selected=new Set(ensureFieldToolCarryV47()),t=ensureFieldTeamV43();
 for(const id of selected){if(id==='lift'&&t.useVehicle)continue;if(id==='cart'&&!t.useVehicle)continue;const kind=id==='medkit'?'medkit':id==='toolkit'?'toolkit':'portable';addZoneLoadV56(loads,cargoZoneForFixedV56(kind),{kind,id,label:FIELD_TOOL_DEFS_V46[id]?.label||id,kg:FIELD_TOOL_MASS_V50[id]||0,volumeL:FIELD_TOOL_VOLUME_L_V54[id]||8,fixed:true})}
 const spareKgById={};for(const [id,n] of Object.entries(fieldSpareLoadV50()))if(n>0){const d=FIELD_SPARE_DEFS_V50[id],kg=n*(d?.weightKg||0),volumeL=n*(FIELD_SPARE_VOLUME_L_V54[id]||4);spareKgById[id]=kg;addZoneLoadV56(loads,cargoZoneForFixedV56('spares'),{kind:'spares',id,label:d?.label||id,kg,volumeL,fixed:true})}
 for(const e of fieldTeamSelectedEquipmentV43()){addZoneLoadV56(loads,cargoZoneForFixedV56('portable'),{kind:'portable',id:e.instanceId,label:equipmentNameV24(e),kg:FIELD_EQUIPMENT_MASS_V50[e.type]||4,volumeL:FIELD_EQUIPMENT_VOLUME_L_V54[e.type]||10,fixed:true})}
 return loads
}
function zoneCapacityIssuesV56(loads,globalAnchorLimit=fieldCargoGeometryV54().anchors){const defs=cargoZoneDefsV56(),issues=[];let anchors=0;for(const [id,z] of Object.entries(loads)){const d=defs[id];anchors+=z.anchors;if(z.kg>d.localKg+1e-6)issues.push(`${d.label}局部載荷 ${z.kg.toFixed(1)}kg 超過 ${d.localKg}kg`);if(z.volumeL>d.volumeL+1e-6)issues.push(`${d.label}體積 ${z.volumeL.toFixed(0)}L 超過 ${d.volumeL}L`);if(z.anchors>(d.localAnchors||0))issues.push(`${d.label}需要 ${z.anchors} 個固定點，但此區只能配置 ${d.localAnchors||0} 個`)}if(anchors>globalAnchorLimit)issues.push(`全車大型固定點 ${anchors}/${globalAnchorLimit} 超額`);return issues}
function cargoBalanceV56(loads){let kg=0,moment=0;for(const z of Object.values(loads)){kg+=z.kg;moment+=z.kg*z.pos}const cg=kg>0?moment/kg:.5,offset=Math.abs(cg-.5),stateLabel=offset<=.10?'平衡':offset<=.18?'可接受':offset<=.26?'偏載':'危險偏載';return {kg,cg,offset,label:stateLabel,wearFactor:1+offset*1.9}}
function zoneFreeV56(loads,zone){const d=cargoZoneDefsV56()[zone],z=loads[zone];return {kg:Math.max(0,d.localKg-z.kg),volumeL:Math.max(0,d.volumeL-z.volumeL),anchors:Math.max(0,(d.localAnchors||0)-z.anchors)}}
function recoveryZoneOrderV56(){const defs=cargoZoneDefsV56(),pref=cargoZoneForFixedV56('recovery'),ids=Object.keys(defs);if(ids.length===1)return ids;return [pref,...CARGO_ZONE_ORDER_V56.filter(x=>x!==pref&&defs[x]),...ids.filter(x=>x!==pref&&!CARGO_ZONE_ORDER_V56.includes(x))]}
function packResourceIntoZonesV56(loads,k,count){let left=Math.max(0,+count||0),packed=0;const w=RES_WEIGHT[k]||1,v=FIELD_RESOURCE_VOLUME_L_V54[k]||Math.max(.1,w*1.15),byZone={};for(const zone of recoveryZoneOrderV56()){if(left<=0)break;const f=zoneFreeV56(loads,zone),max=Math.max(0,Math.floor(Math.min(f.kg/w,f.volumeL/v))),take=Math.min(left,max);if(take<=0)continue;addZoneLoadV56(loads,zone,{kind:'resource',id:k,label:RES_LABELS[k]||k,kg:take*w,volumeL:take*v,dynamic:true});byZone[zone]=(byZone[zone]||0)+take;packed+=take;left-=take}return {packed,left,byZone}}
function accessDepthHoursV56(loads,zone){const defs=cargoZoneDefsV56();if(!defs.rear||!defs.mid||!defs.front)return 0;let blocking=0;if(zone==='mid')blocking+=loads.rear?.dynamicVolumeL||0;if(zone==='front')blocking+=(loads.rear?.dynamicVolumeL||0)+(loads.mid?.dynamicVolumeL||0);blocking+=zone==='rear'?Math.max(0,(loads.rear?.dynamicVolumeL||0)*.35):0;return blocking<=1?0:Math.min(.65,.06+blocking/1400*.32)}
function requiredAccessZonesV56(stop){const zones=new Set(),tasks=stopSubtaskDefsV45(stop);for(const task of tasks){const st=subtaskToolStatusV46(stop,task);for(const tool of st.tools||[]){const kind=tool.id==='medkit'?'medkit':tool.id==='toolkit'?'toolkit':'portable';zones.add(cargoZoneForFixedV56(kind))}}const needs=stopSpareNeedsV50(stop);if(Object.keys(needs).length)zones.add(cargoZoneForFixedV56('spares'));return [...zones]}
function simulateCargoLayoutV56(){
 ensureCargoLayoutV56();const loads=fixedZoneLoadsV56(),rows=[],issues=[...zoneCapacityIssuesV56(loads)];const capacity=fieldCargoCapacityV50(),geom=fieldCargoGeometryV54();let globalKg=Object.values(loads).reduce((a,z)=>a+z.kg,0),globalL=Object.values(loads).reduce((a,z)=>a+z.volumeL,0),globalAnchors=0,maxKg=globalKg,maxL=globalL,maxAnchors=0;
 if(globalKg>capacity+1e-6)issues.push(`出發固定裝載超重 ${(globalKg-capacity).toFixed(1)}kg`);if(globalL>geom.volumeL+1e-6)issues.push(`出發固定裝載體積超出 ${(globalL-geom.volumeL).toFixed(0)}L`);
 for(const stop of ensureItineraryV27().stops){const name=mapLoc(stop.location)?.name||stop.location,beforeKg=globalKg,beforeL=globalL,events=[],accessZones=requiredAccessZonesV56(stop);let accessHours=0;for(const z of accessZones)accessHours=Math.max(accessHours,accessDepthHoursV56(loads,z));
  const passengers=rescuePassengerCountV52(stop);if(passengers&&Number.isFinite(geom.seats)){const seats=fieldTeamSizeV43()+passengers;events.push(`救援座位 ${seats}/${geom.seats}`);if(seats>geom.seats)issues.push(`${name}：救援後需要 ${seats} 席，但車艙只有 ${geom.seats} 席`)}
  let handlingHours=accessHours;
  if(stop.action==='search'){let addedKg=0,addedL=0;for(const k of RES_ORDER){const av=Math.max(0,+state.locations?.[stop.location]?.remaining?.[k]||0);if(av<=0)continue;const roomKg=Math.max(0,capacity-globalKg),roomL=Math.max(0,geom.volumeL-globalL),w=RES_WEIGHT[k]||1,v=FIELD_RESOURCE_VOLUME_L_V54[k]||Math.max(.1,w*1.15),maxGlobal=Math.max(0,Math.floor(Math.min(roomKg/w,roomL/v))),want=Math.min(av,maxGlobal);if(want<=0)continue;const p=packResourceIntoZonesV56(loads,k,want);if(p.packed){const kg=p.packed*w,l=p.packed*v;globalKg+=kg;globalL+=l;addedKg+=kg;addedL+=l}}
   if(addedKg>0){events.push(`搜索裝載 +${addedKg.toFixed(1)}kg / ${addedL.toFixed(0)}L`);handlingHours+=.05+Math.min(.28,addedKg/500*.22)}
  }
  if(stop.action==='asset'){const a=assetAtStopV46(stop);if(a){const st=state.assets?.[a.id],allowed=!st||st.owner==='world'||st.owner==='player';if(allowed){const zone=cargoAssetZoneV56(stop,a),sp=assetSpaceV54(a.id),f=zoneFreeV56(loads,zone),globalAnchorFree=Math.max(0,geom.anchors-globalAnchors);const kgFail=globalKg+a.weight>capacity+1e-6||f.kg+1e-6<a.weight,lFail=globalL+sp.volumeL>geom.volumeL+1e-6||f.volumeL+1e-6<sp.volumeL,aFail=f.anchors<sp.anchors||globalAnchorFree<sp.anchors;if(kgFail)issues.push(`${name}：${CARGO_ZONE_LABEL_V56[zone]||zone}無法承受${a.name}的重量`);if(lFail)issues.push(`${name}：${a.name}無法放入${CARGO_ZONE_LABEL_V56[zone]||zone}的可用體積`);if(aFail)issues.push(`${name}：${a.name}在${CARGO_ZONE_LABEL_V56[zone]||zone}缺少固定點`);if(!kgFail&&!lFail&&!aFail){addZoneLoadV56(loads,zone,{kind:'asset',id:a.id,label:a.name,kg:a.weight,volumeL:sp.volumeL,anchors:sp.anchors,dynamic:true});globalKg+=a.weight;globalL+=sp.volumeL;globalAnchors+=sp.anchors;events.push(`${a.name} → ${CARGO_ZONE_LABEL_V56[zone]||zone}`);handlingHours+=.06+Math.min(.28,a.weight/900*.24)}}}}
  const localIssues=zoneCapacityIssuesV56(loads,geom.anchors);for(const x of localIssues)issues.push(`${name}：${x}`);const balance=cargoBalanceV56(loads);if(balance.offset>.30)issues.push(`${name}：貨艙重心偏移 ${(balance.offset*100).toFixed(0)}%，超過安全出車範圍`);else if(balance.offset>.18)events.push(`重心偏載 ${(balance.offset*100).toFixed(0)}%`);
  maxKg=Math.max(maxKg,globalKg);maxL=Math.max(maxL,globalL);maxAnchors=Math.max(maxAnchors,globalAnchors);rows.push({stop,name,beforeKg,beforeL,afterKg:globalKg,afterL:globalL,anchors:globalAnchors,events,accessHours,handlingHours,balance,loads:JSON.parse(JSON.stringify(loads)),freeKg:Math.max(0,capacity-globalKg),freeL:Math.max(0,geom.volumeL-globalL)})
 }
 const balance=cargoBalanceV56(loads);return {capacity,volumeL:geom.volumeL,anchors:geom.anchors,seats:geom.seats,geometry:geom,fixed:Object.values(fixedZoneLoadsV56()).reduce((a,z)=>a+z.kg,0),fixedVolumeL:Object.values(fixedZoneLoadsV56()).reduce((a,z)=>a+z.volumeL,0),rows,loads,maxUsed:maxKg,maxVolumeL:maxL,maxAnchors,endUsed:globalKg,endVolumeL:globalL,endFree:Math.max(0,capacity-globalKg),endFreeVolumeL:Math.max(0,geom.volumeL-globalL),endAnchorFree:Math.max(0,geom.anchors-globalAnchors),balance,issues:[...new Set(issues)],ok:issues.length===0}
}
/* New layout model is the sole cargo validator; V52 remains the base for non-cargo team/tool/spare checks. */
fieldTeamValidationV43=function(e){const v=_fieldTeamValidationV52(e),layout=simulateCargoLayoutV56(),issues=[...v.issues,...layout.issues];return {...v,cargoFlow:layout,cargoGeometry:layout,cargoLayout:layout,ok:issues.length===0,issues:[...new Set(issues)]}};

function cargoExtraHoursV56(stop){if(!stop)return 0;if(ensureFieldTeamV43().active)return actualCargoAccessHoursV56(stop);const row=simulateCargoLayoutV56().rows.find(r=>r.stop===stop);return Math.max(0,+row?.handlingHours||0)}
const _stopActionHoursV56=stopActionHoursV27;
stopActionHoursV27=function(stop){return Math.round((_stopActionHoursV56(stop)+cargoExtraHoursV56(stop))*20)/20};

function ensureActualZoneStateV56(){const c=ensureDynamicCargoV52();if(!c.resourceZones)c.resourceZones={};if(!c.assetZones)c.assetZones={};return c}
function actualZoneLoadsV56(){const loads=fixedZoneLoadsV56(),c=ensureActualZoneStateV56();for(const [k,zmap] of Object.entries(c.resourceZones||{})){const w=RES_WEIGHT[k]||1,v=FIELD_RESOURCE_VOLUME_L_V54[k]||Math.max(.1,w*1.15);for(const [zone,n] of Object.entries(zmap||{}))if(n>0&&loads[zone])addZoneLoadV56(loads,zone,{kind:'resource',id:k,label:RES_LABELS[k]||k,kg:n*w,volumeL:n*v,dynamic:true})}for(const id of c.assets||[]){const zone=c.assetZones?.[id]||Object.keys(loads)[0],a=assetDefs.find(x=>x.id===id),sp=assetSpaceV54(id);if(a&&loads[zone])addZoneLoadV56(loads,zone,{kind:'asset',id,label:a.name,kg:a.weight,volumeL:sp.volumeL,anchors:sp.anchors,dynamic:true})}return loads}
const _dynamicCargoSnapshotV56=dynamicCargoSnapshotV52;
dynamicCargoSnapshotV52=function(){const base=_dynamicCargoSnapshotV56(),loads=actualZoneLoadsV56(),balance=cargoBalanceV56(loads),localIssues=zoneCapacityIssuesV56(loads,fieldCargoGeometryV54().anchors);return {...base,zoneLoads:loads,balance,layoutIssues:localIssues,ok:base.ok&&!localIssues.length&&balance.offset<=.30}}
function actualCargoAccessHoursV56(stop){const loads=actualZoneLoadsV56();let h=0;for(const z of requiredAccessZonesV56(stop))h=Math.max(h,accessDepthHoursV56(loads,z));return h}
function packActualResourceV56(k,count){const c=ensureActualZoneStateV56(),loads=actualZoneLoadsV56(),snap=dynamicCargoSnapshotV52(),w=RES_WEIGHT[k]||1,v=FIELD_RESOURCE_VOLUME_L_V54[k]||Math.max(.1,w*1.15),globalMax=Math.max(0,Math.floor(Math.min(snap.free/w,snap.freeVolumeL/v))),p=packResourceIntoZonesV56(loads,k,Math.min(count,globalMax));if(p.packed){c.resources[k]=(c.resources[k]||0)+p.packed;c.resourceZones[k]=c.resourceZones[k]||{};for(const [z,n] of Object.entries(p.byZone))c.resourceZones[k][z]=(c.resourceZones[k][z]||0)+n}return p.packed}
collectStopLootV27=function(loc){const t=ensureFieldTeamV43();if(!t.active)return _collectStopLootV54(loc);const c=ensureActualZoneStateV56(),rem=state.locations[loc.id].remaining,gain={};for(const k of RES_ORDER){const av=Math.max(0,+rem[k]||0);if(av<=0)continue;const take=packActualResourceV56(k,av);if(take>0){rem[k]-=take;gain[k]=take}}state.locations[loc.id].searched=true;state.intel[loc.id]={day:state.day,verifiedDay:state.day,summary:summarizeRemaining(rem),source:'行程實地搜索',confidence:100};discoverAssetsAt(loc.id);tutorialWaterGain(gain);const kg=dynamicResourceMassV52(gain),vol=dynamicResourceVolumeV54(gain),after=dynamicCargoSnapshotV52();c.history.push({day:state.day,location:loc.id,type:'search',kg,volumeL:vol,gain:{...gain},usedKg:after.used,usedVolumeL:after.usedVolumeL});log(`${loc.name}行程搜索：${Object.entries(gain).map(([k,v])=>`${RES_LABELS[k]||k}+${v}`).join('、')||'貨艙已沒有可用重量／體積／區域空間'}｜${after.used.toFixed(1)}kg / ${after.usedVolumeL.toFixed(0)}L。`,'good')};
loadAssetIntoDynamicCargoV52=function(stop){const t=ensureFieldTeamV43();if(!t.active||stop?.action!=='asset'||stop._dynamicAssetLoadedV52)return true;const a=assetAtStopV46(stop);if(!a)return true;const st=state.assets?.[a.id];if(st&&st.owner!=='world'&&st.owner!=='player')return false;const c=ensureActualZoneStateV56(),zone=cargoAssetZoneV56(stop,a),loads=actualZoneLoadsV56(),f=zoneFreeV56(loads,zone),snap=dynamicCargoSnapshotV52(),sp=assetSpaceV54(a.id);if(snap.free+1e-6<a.weight)return pauseItineraryV27(`${a.name}需要 ${a.weight}kg，但只剩 ${snap.free.toFixed(1)}kg 載重`),false;if(snap.freeVolumeL+1e-6<sp.volumeL||f.volumeL+1e-6<sp.volumeL)return pauseItineraryV27(`${a.name}無法放入${CARGO_ZONE_LABEL_V56[zone]||zone}；該區剩餘 ${f.volumeL.toFixed(0)}L`),false;if(f.kg+1e-6<a.weight)return pauseItineraryV27(`${CARGO_ZONE_LABEL_V56[zone]||zone}局部載荷不足以承受${a.name}`),false;if(f.anchors<sp.anchors||snap.anchorFree<sp.anchors)return pauseItineraryV27(`${a.name}在${CARGO_ZONE_LABEL_V56[zone]||zone}缺少固定點`),false;c.assets.push(a.id);c.assetZones[a.id]=zone;if(st){st.inTransit=true;st.location=ensureItineraryV27().current||stop.location}stop._dynamicAssetLoadedV52=true;const after=dynamicCargoSnapshotV52();c.history.push({day:state.day,location:stop.location,type:'asset',assetId:a.id,kg:a.weight,volumeL:sp.volumeL,anchors:sp.anchors,zone,usedKg:after.used,usedVolumeL:after.usedVolumeL});log(`${a.name}固定於${CARGO_ZONE_LABEL_V56[zone]||zone}；重心 ${after.balance.label}。`,'major');return true};
const _activateFieldTeamV56=activateFieldTeamV43;
activateFieldTeamV43=function(e){const r=_activateFieldTeamV56(e);if(r?.ok){const c=ensureActualZoneStateV56();c.resourceZones={};c.assetZones={};c.loadSequence=[]}return r};
const _unloadDynamicCargoV56=unloadDynamicCargoV52;
unloadDynamicCargoV52=function(home){const c=ensureActualZoneStateV56();_unloadDynamicCargoV56(home);c.resourceZones={};c.assetZones={};c.loadSequence=[];saveGame(false)};

/* Unbalanced or heavily loaded cargo costs more fuel and wears the vehicle faster. */
const _vehicleDriveCostV56=vehicleDriveCostV32;
vehicleDriveCostV32=function(distance,hours,opts={}){const c=_vehicleDriveCostV56(distance,hours,opts),t=ensureFieldTeamV43();if(!(t.useVehicle&&state.gear?.vehicle))return c;const snap=t.active?dynamicCargoSnapshotV52():null,loadRatio=snap?clamp(snap.used/Math.max(1,snap.capacity),0,1):0,balance=snap?.balance||{offset:0};const factor=1+loadRatio*.055+balance.offset*.16;return {...c,fuelL:c.fuelL*factor,cargoFactor:factor}}
const _consumeVehicleDriveV56=consumeVehicleDriveV32;
consumeVehicleDriveV32=function(distance,hours,opts={}){const r=_consumeVehicleDriveV56(distance,hours,opts);if(!r?.ok||!ensureFieldTeamV43().active)return r;const snap=dynamicCargoSnapshotV52(),risk=Math.max(1,+mapLoc(ensureItineraryV27().current)?.risk||1),extra=Math.max(0,+distance||0)*(.0035*clamp(snap.used/Math.max(1,snap.capacity),0,1)+.013*snap.balance.offset*risk),e=coolingVehicleV32();if(e){e.condition=clamp((e.condition??100)-extra,0,100);state.vehicle.condition=Math.min(state.vehicle.condition??100,e.condition)}return {...r,cargoWear:extra}}

function cargoZoneOptionsV56(selected){return Object.entries(cargoZoneDefsV56()).map(([id,d])=>`<option value="${id}" ${selected===id?'selected':''}>${d.label} · ${d.volumeL}L · 局部 ${d.localKg}kg</option>`).join('')}
function cargoLayoutHtmlV56(){
 const t=ensureFieldTeamV43(),locked=t.active,l=ensureCargoLayoutV56(),sim=t.active?null:simulateCargoLayoutV56(),loads=t.active?actualZoneLoadsV56():sim.loads,balance=cargoBalanceV56(loads),assetRows=ensureItineraryV27().stops.map((s,i)=>{if(s.action!=='asset')return '';const a=assetAtStopV46(s);if(!a)return '';const z=cargoAssetZoneV56(s,a),sp=assetSpaceV54(a.id);return `<label class="cargo-layout-row"><span><b>STOP ${i+1} · ${a.name}</b><small>${a.weight}kg · ${sp.volumeL}L · 固定點 ${sp.anchors}</small></span><select data-cargo-asset-zone="${s.id}" ${locked?'disabled':''}>${cargoZoneOptionsV56(z)}</select></label>`}).join('');
 const policy=[['medkit','醫療包'],['toolkit','工具箱'],['spares','維修備件'],['portable','可攜設備'],['recovery','搜索回收物資優先區']].map(([k,n])=>`<label class="cargo-layout-row"><span><b>${n}</b><small>${k==='recovery'?'裝滿後會向其他區溢出':'深處被後續貨物遮擋時，現場取用會增加重整工時'}</small></span><select data-cargo-policy="${k}" ${locked?'disabled':''}>${cargoZoneOptionsV56(l.policy[k])}</select></label>`).join('');
 const zoneRows=Object.entries(loads).map(([id,z])=>{const d=cargoZoneDefsV56()[id];return `<div class="cargo-zone-meter"><b>${d.label}</b><span>${z.kg.toFixed(1)} / ${d.localKg}kg</span><span>${z.volumeL.toFixed(0)} / ${d.volumeL}L</span><span>固定 ${z.anchors}/${d.localAnchors||0}</span></div>`}).join('');
 return `<div class="cargo-layout-box ${balance.offset>.30?'blocked':''}"><div class="field-role-head"><div><span>CARGO STOW / ACCESS</span><h4>貨艙配置與取用順序</h4></div><b>${balance.label} · CG ${balance.cg.toFixed(2)}</b></div><p class="muted">後艙最接近車門；放在中艙／前艙的工具若被後續回收物資遮擋，現場會先消耗卸出／重整工時。重物偏在車頭或車尾會增加油耗與路段車況損耗。</p><div class="cargo-zone-grid">${zoneRows}</div><div class="cargo-layout-list">${policy}${assetRows}</div>${sim?.rows?.some(r=>r.accessHours>0)?`<div class="cargo-access-note">目前規劃中有被遮擋取用：${sim.rows.filter(r=>r.accessHours>0).map(r=>`${r.name} +${r.accessHours.toFixed(2)}h`).join(' · ')}</div>`:''}</div>`
}
const _subtaskPlannerHtmlV56=subtaskPlannerHtmlV46;
subtaskPlannerHtmlV46=function(){const html=_subtaskPlannerHtmlV56(),box=cargoLayoutHtmlV56();return html.replace('<div class="parallel-stop-list">',box+'<div class="parallel-stop-list">')};
const _bindItineraryPlannerV56=bindItineraryPlannerV27;
bindItineraryPlannerV27=function(){_bindItineraryPlannerV56();document.querySelectorAll('[data-cargo-policy]').forEach(x=>x.onchange=()=>setCargoPolicyV56(x.dataset.cargoPolicy,x.value));document.querySelectorAll('[data-cargo-asset-zone]').forEach(x=>x.onchange=()=>setCargoAssetZoneV56(x.dataset.cargoAssetZone,x.value))};
ensureCargoLayoutV56();
