// v14.6 Batch 3 — movable obstacles, forced access, broken equipment, dismantling.
(function(){
 const PARTS_V120={
  'item-copper-wire-bundle':{name:'銅線束',weightKg:.6,category:'part'},
  'item-bearing':{name:'軸承',weightKg:.4,category:'part'},
  'item-drive-belt':{name:'傳動皮帶',weightKg:.35,category:'part'},
  'item-small-electric-motor':{name:'小型電動馬達',weightKg:1.2,category:'part'},
  'item-fan-blade-assembly':{name:'風扇葉片總成',weightKg:.8,category:'part'},
  'item-sheet-metal':{name:'鈑金片',weightKg:3,category:'material'},
  'item-fastener-box':{name:'螺栓螺絲盒',weightKg:.5,category:'material'}
 };
 const OBJECTS_V120={
  homes:[{id:'homes-fallen-shelf',name:'倒下的層架',kind:'movable',hours:.5}],
  store:[{id:'store-stuck-shutter',name:'卡死的鐵捲門',kind:'forced-door',tool:'item-crowbar',hours:.5}],
  clinic:[{id:'clinic-broken-fan',name:'故障排風扇',kind:'broken-equipment',inspectHours:.5,dismantleHours:1,tool:'item-insulated-pliers',yields:['item-copper-wire-bundle','item-small-electric-motor','item-fan-blade-assembly']}],
  hardware:[{id:'hardware-damaged-motor',name:'燒毀的台式機具',kind:'broken-equipment',inspectHours:.5,dismantleHours:1,tool:'item-adjustable-wrench',yields:['item-bearing','item-drive-belt','item-fastener-box']}],
  warehouse:[{id:'warehouse-pallet',name:'擋住通道的棧板',kind:'movable',hours:1},{id:'warehouse-bent-panel',name:'變形金屬護板',kind:'dismantlable',inspectHours:.5,dismantleHours:1,tool:'item-crowbar',yields:['item-sheet-metal','item-fastener-box']}]
 };
 function cloneV120(){const out={};for(const [loc,list] of Object.entries(OBJECTS_V120))out[loc]=list.map(o=>({...o,moved:false,opened:false,inspected:false,dismantled:false,yields:[...(o.yields||[])]}));return out}
 function ensureV120(s=state){s.scenePhysicalV120=s.scenePhysicalV120&&typeof s.scenePhysicalV120==='object'?s.scenePhysicalV120:{};if(!s.scenePhysicalV120.locations)s.scenePhysicalV120.locations=cloneV120();return s.scenePhysicalV120}
 function hasV120(id,s=state){if(typeof ensurePhysicalInventoryV115==='function')ensurePhysicalInventoryV115(s);return [...(s.backpack?.items||[]),...(s.shelterStorage?.items||[])].some(x=>x?.catalogId===id)}
 function spendV120(h){h=Math.max(0,Number(h)||0);if(state.day>=30)return true;if(!Number.isFinite(state.hoursLeft)||state.hoursLeft+1e-9<h){toast(`目前沒有足夠時間；需要 ${h}h`);return false}state.hoursLeft=Math.max(0,Math.round((state.hoursLeft-h)*10)/10);return true}
 function itemV120(id){const d=PARTS_V120[id];return d?{id,catalogId:id,name:d.name,category:d.category,weightKg:d.weightKg}:null}
 function objectV120(loc,id){return ensureV120().locations?.[loc]?.find(o=>o.id===id)||null}
 function currentLocV120(){return typeof ensureExplorationV113==='function'?ensureExplorationV113().current:'base'}
 function observedV120(loc){return state.explorationV118?.observed?.[loc]===true}
 function moveV120(loc,id){const o=objectV120(loc,id);if(!o||o.moved)return false;if(!spendV120(o.hours||.5))return false;o.moved=true;log(`你移開了${o.name}。`,'good');render();return true}
 function openV120(loc,id){const o=objectV120(loc,id);if(!o||o.opened)return false;if(o.tool&&!hasV120(o.tool)){toast('你手上沒有能處理它的工具');return false}if(!spendV120(o.hours||.5))return false;o.opened=true;log(`你打開了${o.name}後方的通道。`,'good');render();return true}
 function inspectV120(loc,id){const o=objectV120(loc,id);if(!o||o.inspected||o.dismantled)return false;if(!spendV120(o.inspectHours||.5))return false;o.inspected=true;log(`你檢查了${o.name}。`,'good');render();return true}
 function dismantleV120(loc,id){const o=objectV120(loc,id);if(!o||o.dismantled||!o.inspected)return false;if(o.tool&&!hasV120(o.tool)){toast('你缺少合適的工具');return false}if(!spendV120(o.dismantleHours||1))return false;const produced=[];for(const id2 of o.yields||[]){const it=itemV120(id2);if(!it)continue;const r=typeof addItemToBackpackV115==='function'?addItemToBackpackV115(it):{ok:false};if(!r.ok){toast(r.reason||'背包放不下拆出的零件');return false}produced.push(it.name)}o.dismantled=true;o.yields=[];log(`你拆開了${o.name}${produced.length?`，取得${produced.join('、')}`:''}。`,'good');render();return true}
 function htmlV120(o){if(o.kind==='movable')return o.moved?`<article class="scene-object-v120 done"><div><b>${o.name}</b><small>已移開</small></div></article>`:`<article class="scene-object-v120"><div><b>${o.name}</b><small>擋住部分通道</small></div><button data-move-v120="${o.id}">移開 · ${o.hours}h</button></article>`;if(o.kind==='forced-door')return o.opened?`<article class="scene-object-v120 done"><div><b>${o.name}</b><small>已打開</small></div></article>`:`<article class="scene-object-v120"><div><b>${o.name}</b><small>目前打不開</small></div><button data-open-v120="${o.id}">處理 · ${o.hours}h</button></article>`;if(o.dismantled)return `<article class="scene-object-v120 done"><div><b>${o.name}</b><small>已拆解</small></div></article>`;if(!o.inspected)return `<article class="scene-object-v120"><div><b>${o.name}</b><small>${o.kind==='broken-equipment'?'看起來已故障':'需要先查看'}</small></div><button data-inspect-v120="${o.id}">檢查 · ${o.inspectHours}h</button></article>`;return `<article class="scene-object-v120"><div><b>${o.name}</b><small>可以拆解；實際取得內容要拆開才知道</small></div><button data-dismantle-v120="${o.id}">拆解 · ${o.dismantleHours}h</button></article>`}
 function renderPanelV120(){if(!state.flags?.hardFogOpeningV112)return;const map=document.getElementById('map');if(!map)return;map.querySelector('.scene-physical-v120')?.remove();const loc=currentLocV120();if(!observedV120(loc))return;const list=ensureV120().locations?.[loc]||[];if(!list.length)return;const p=document.createElement('section');p.className='scene-physical-v120';p.innerHTML=`<div class="scene-head-v120"><b>環境物件</b><small>只顯示你在這個地點實際看見的東西</small></div>${list.map(htmlV120).join('')}`;map.appendChild(p);p.querySelectorAll('[data-move-v120]').forEach(b=>b.onclick=()=>moveV120(loc,b.dataset.moveV120));p.querySelectorAll('[data-open-v120]').forEach(b=>b.onclick=()=>openV120(loc,b.dataset.openV120));p.querySelectorAll('[data-inspect-v120]').forEach(b=>b.onclick=()=>inspectV120(loc,b.dataset.inspectV120));p.querySelectorAll('[data-dismantle-v120]').forEach(b=>b.onclick=()=>dismantleV120(loc,b.dataset.dismantleV120))}
 function stylesV120(){if(document.getElementById('batch3StylesV120'))return;const s=document.createElement('style');s.id='batch3StylesV120';s.textContent=`.scene-physical-v120{position:absolute;right:18px;top:74px;z-index:11;width:min(300px,34%);display:grid;gap:8px;padding:10px;border:1px solid rgba(180,210,210,.22);background:rgba(9,17,19,.92);border-radius:12px}.scene-head-v120,.scene-object-v120>div{display:grid;gap:2px}.scene-head-v120 small,.scene-object-v120 small{opacity:.68}.scene-object-v120{display:grid;gap:8px;padding:9px;border:1px solid rgba(180,210,210,.12);border-radius:9px}.scene-object-v120.done{opacity:.62}.scene-object-v120 button{justify-self:start}`;document.head.appendChild(s)}
 const prevRenderMapV120=renderMap;renderMap=function(){const out=prevRenderMapV120();stylesV120();queueMicrotask(renderPanelV120);return out};const prevRenderV120=render;render=function(){const out=prevRenderV120();stylesV120();queueMicrotask(renderPanelV120);return out};ensureV120();stylesV120();
 window.ensureScenePhysicalV120=ensureV120;window.moveSceneObjectV120=moveV120;window.openSceneObjectV120=openV120;window.inspectSceneObjectV120=inspectV120;window.dismantleSceneObjectV120=dismantleV120;
})();