function considerMigration(s){if(s.population<=0||requestExists(s))return;let destination=state.day>=30&&state.base.ventCapacity>0?'vent':'subway';if(destination==='vent'){const people=Math.min(s.population,Math.max(2,Math.ceil(s.population*.55)));const req={name:s.name,people,reason:'原聚落水與溫控無法維持',settlement:s.id,day:state.day};if(state.ration.intake==='closed'){s.trust-=1;log(`${s.name}聽說中央站封閉入口，轉而尋找其他地下空間。`,'bad')}else if(state.ration.intake==='open'&&state.base.population+people<=state.base.ventCapacity){state.base.population+=people;s.population-=people;log(`${s.name}有 ${people} 人自動遷入中央通風站。`,'good')}else{state.pendingRequests.push(req);log(`${s.name}有 ${people} 人抵達中央站，等待你的決定。`,'major')}}else{s.location='subway';s.health=Math.min(100,s.health+5);log(`${s.name}因缺水與高溫，遷往地鐵維修站。`,'major')}state.flags.lastMigration=state.day}
function npcAssetTick(){
 if(state.day<10||state.day%3!==0)return;
 const candidates=assetDefs.filter(a=>{const st=state.assets[a.id];return !st.transported&&st.owner==='world'&&state.locations[a.location]?.searched===false});
 if(!candidates.length)return;
 const a=candidates[Math.floor(Math.random()*candidates.length)],st=state.assets[a.id];
 const groups=Object.values(state.settlements).filter(x=>x.population>=4);if(!groups.length)return;
 const g=groups[Math.floor(Math.random()*groups.length)];st.discovered=true;st.owner=g.id;st.location=g.location;state.logistics.npcMoved++;
 recordFlow(locations.find(l=>l.id===a.location)?.name||'城市',g.name,'大型資產',1);log(`${g.name}先一步搬走了${a.name}。你仍可談交換，或直接截胡。`,'major');
}
function npcDaily(){Object.values(state.npcs).forEach(n=>{if(!n.alive)return;n.stock.water=Math.max(0,(n.stock.water||0)-2);n.stock.food=Math.max(0,(n.stock.food||0)-1);n.need=normalizeNeed(n);if(n.stock.water===0&&state.day>18){if(n.trust>1&&state.resources.water>=4){state.resources.water-=4;n.stock.water=4;log(`${n.name}因信任你而前來求水。`,'good')}else if(Math.random()<.16){n.alive=false;log(`${n.name}因長期缺水死亡。`,'bad')}}});if(state.day%phaseBand().npcSearch===0)npcSearch();npcAssetTick();settlementTick();settlementTradeTick()}

function availableWorkers(){return Math.max(1,state.base.population)}
function assignedWorkers(){return Object.entries(state.workforce).filter(([k])=>k!=='rest').reduce((a,[k,v])=>a+(+v||0),0)}
function workEfficiency(role){let e=1-state.fatigue/140;if(state.ration.water<2.5)e-=.1;if(state.ration.food<1)e-=.08;if(state.base.condition<60)e-=.12;const bonus={water:state.training.hvac*.02,cooling:state.training.hvac*.04,power:state.training.electric*.04,medical:state.training.medical*.05,logistics:0,maintenance:(state.training.hvac+state.training.electric)*.02,core:(state.training.hvac+state.training.electric)*.025}[role]||0;return clamp(e+bonus,.35,1.35)}
function workforceTick(){if(state.day<30||state.base.ventilation===0)return;const w=state.workforce, pop=availableWorkers();const assigned=assignedWorkers();const rest=Math.max(0,pop-assigned)+(w.rest||0);state.fatigue=clamp(state.fatigue + assigned/Math.max(1,pop)*7 - rest/Math.max(1,pop)*9,0,100);
 let waterGain=Math.floor((w.water||0)*1.1*workEfficiency('water'));if(waterGain>0&&state.base.waterTreatment>0){state.resources.water+=waterGain}
 let powerGain=Math.floor((w.power||0)*.8*workEfficiency('power'));if(powerGain>0)state.resources.battery=Math.min(state.base.storageKWh,state.resources.battery+powerGain);
 let maint=(w.maintenance||0)*1.2*workEfficiency('maintenance');if(maint>0)state.base.condition=Math.min(100,state.base.condition+maint);
 let cool=(w.cooling||0)*.8*workEfficiency('cooling');if(cool>0&&state.base.condition<100)state.base.condition=Math.min(100,state.base.condition+cool*.35);
 if((w.medical||0)>0&&state.day%3===0&&state.base.trust<15)state.base.trust+=1;
 if((w.logistics||0)>0&&state.day%2===0){state.resources.parts+=Math.floor((w.logistics||0)*.3*workEfficiency('logistics'))}
 if(state.npcs.chen?.alive&&w.cooling>0)state.training.hvac=clamp(state.training.hvac+.18,0,5);if(state.npcs.lin?.alive&&w.medical>0)state.training.medical=clamp(state.training.medical+.16,0,5);if(w.power>0)state.training.electric=clamp(state.training.electric+.12,0,5);
}
function privateEconomyTick(){if(state.day<30||state.base.population<4)return;const pressure=(state.ration.water<2.5?1:0)+(state.resources.water<dailyWaterNeed()*2?1:0);if(pressure&&Math.random()<.28){let amt=Math.min(state.resources.water,2+Math.floor(Math.random()*4));if(amt>0){state.resources.water-=amt;state.privatePool.water+=amt;log(`中央站有人把 ${amt}L 水轉入私人存量。配給壓力正在改變內部經濟。`,'bad')}}else if(state.privatePool.water>0&&state.base.trust>5&&Math.random()<.24){let amt=Math.min(state.privatePool.water,3);state.privatePool.water-=amt;state.resources.water+=amt;log(`居民把 ${amt}L 私人存水重新投入公共水箱。`,'good')}}
function chainLevel(name){return state.eventChains?.[name]?.level||0}
function setChain(name,level,label){const c=state.eventChains[name]||(state.eventChains[name]={level:0});level=clamp(level,0,3);if(level===c.level)return;const old=c.level;c.level=level;const words=['穩定','出現前兆','壓力升高','危機'];if(level>old)log(`${label}事件鏈：${words[level]}。` ,level>=3?'bad':'major');else if(level<old)log(`${label}事件鏈回落至「${words[level]}」。`,'good')}
function updateEventChains(){const waterScore=daysOfWater()<=1?3:daysOfWater()<=3?2:daysOfWater()<=5?1:0;setChain('water',waterScore,'供水');const gridScore=state.day<30?0:(state.base.condition<40||coolingLoadPct()>115?3:state.base.condition<58||coolingLoadPct()>100?2:state.base.condition<75||coolingLoadPct()>85?1:0);setChain('grid',gridScore,'冷卻／電網');const endangered=Object.values(state.settlements).filter(x=>x.population>0&&(x.status==='缺水'||x.status==='危急缺水')).length;setChain('migration',endangered>=2?3:endangered===1?2:(state.pendingRequests.length?1:0),'人口遷移');const cp=coreSchedulePressure();setChain('core',cp>=4?3:cp>=2?2:cp>=1?1:0,'終局時程');if(chainLevel('water')===3&&state.privatePool.water>0){const amt=Math.min(state.privatePool.water,4);state.privatePool.water-=amt;state.resources.water+=amt;log(`供水危機迫使居民釋出 ${amt}L 私人存水，暫時延後崩潰。`,'good')}if(chainLevel('grid')===3&&state.resources.battery>2){state.resources.battery=Math.max(0,state.resources.battery-2);log('高負載保護啟動，額外消耗 2 kWh 儲能以避免冷卻系統立即停機。','bad')}}
function buildBrief(){const issues=[];if(daysOfWater()<5)issues.push({sev:5-daysOfWater(),text:`公共飲水約 ${daysOfWater()} 天；每日需求 ${dailyWaterNeed()}L。`,act:state.base.waterTreatment<3?'優先找水、濾芯或增加水務人力。':'降低人口壓力或安排新的水源遠征。'});if(foodDays()<4)issues.push({sev:4-foodDays(),text:`食物約 ${foodDays()} 天。`,act:'下一次遠征優先食物，避免讓慢性短缺拖垮人力。'});if(state.day>=30&&state.base.ventilation===0)issues.push({sev:5,text:'中央站尚未形成有效冷卻。',act:'優先啟動中央站初級冷卻；其他工程延後。'});if(state.day>=30&&state.base.condition<70)issues.push({sev:Math.ceil((70-state.base.condition)/10),text:`中央站設備狀況 ${Math.round(state.base.condition)}%。`,act:'增加維護人力或執行預防維護。'});if(overCapacity()>0)issues.push({sev:3,text:`人口超出冷卻容量 ${overCapacity()} 人。`,act:'暫停遷入、擴容或建立外部冷站分流。'});if(state.fatigue>45)issues.push({sev:2,text:`平均疲勞 ${Math.round(state.fatigue)}%。`,act:'減少工作分配，留下更多休息人口。'});if(state.day>=45&&!state.base.core){const p=coreSchedulePressure();issues.push({sev:Math.max(1,p),text:`核心工程 ${state.coreProject.stage}/10；距 Day 60 ${Math.max(0,60-state.day)} 天。`,act:p>=2?'終局工程已落後預期，增加核心工程隊並停止低優先工作。':'時程仍可控，但不要讓工程停工。'})}issues.sort((a,b)=>b.sev-a.sev);const top=issues.slice(0,4);return {day:state.day,risk:riskLabel(),phase:phaseBand().name,water:daysOfWater(),food:foodDays(),issues:top}}
