/* v14.2.2 QA — cargo geometry / volume / hardpoints / passenger space */
const FIELD_RESOURCE_VOLUME_L_V54={water:1,food:1.8,battery:.7,medicine:.25,fuel:1.1,parts:.9,coolant:1.25,filters:2.5,data:.08};
const FIELD_SPARE_VOLUME_L_V54={repairPack:9,sealKit:3,fuseKit:2,coolantKit:9};
const FIELD_TOOL_VOLUME_L_V54={toolkit:24,cart:90,lift:420,medkit:4};
const FIELD_EQUIPMENT_VOLUME_L_V54={coolpack:16,portableFan:6};
const FIELD_ASSET_SPACE_V54={
 generator:{volumeL:680,anchors:1},ibc:{volumeL:1180,anchors:1},compressorA:{volumeL:920,anchors:1},compressorB:{volumeL:860,anchors:1},chiller:{volumeL:1750,anchors:2},pump:{volumeL:310,anchors:0},inverter:{volumeL:410,anchors:1},lift:{volumeL:1480,anchors:2},drum200:{volumeL:235,anchors:1},fireTank:{volumeL:2250,anchors:2}
};
function resourceVolumeV54(k,n){return Math.max(0,+n||0)*(FIELD_RESOURCE_VOLUME_L_V54[k]||Math.max(.1,(RES_WEIGHT[k]||1)*1.15))}
function spareVolumeV54(load=fieldSpareLoadV50()){return Object.entries(load||{}).reduce((l,[id,n])=>l+Math.max(0,+n||0)*(FIELD_SPARE_VOLUME_L_V54[id]||4),0)}
function toolVolumeV54(){const selected=new Set(ensureFieldToolCarryV47()),t=ensureFieldTeamV43();let l=0;for(const id of selected){if(id==='lift'&&t.useVehicle)continue;l+=FIELD_TOOL_VOLUME_L_V54[id]||8}return l}
function portableEquipmentVolumeV54(){return fieldTeamSelectedEquipmentV43().reduce((l,e)=>l+(FIELD_EQUIPMENT_VOLUME_L_V54[e.type]||10),0)}
function assetSpaceV54(id){const a=assetDefs.find(x=>x.id===id);return FIELD_ASSET_SPACE_V54[id]||{volumeL:Math.max(50,(a?.weight||50)*1.7),anchors:a?.need==='vehicle'?1:0}}
function fieldCargoGeometryV54(){
 const t=ensureFieldTeamV43(),members=fieldTeamSizeV43();
 if(t.useVehicle&&state.gear?.vehicle)return {volumeL:state.logistics?.heavyReady?3600:2600,anchors:state.logistics?.heavyReady?3:2,seats:3,label:state.logistics?.heavyReady?'工程車重型貨艙':'工程車貨艙'};
 const cart=ensureFieldToolCarryV47().includes('cart')&&state.gear?.cart;if(cart)return {volumeL:380+Math.max(0,members-1)*45,anchors:0,seats:Infinity,label:'推車／人力裝載'};
 return {volumeL:members*55,anchors:0,seats:Infinity,label:'人力攜行'}
}
function fixedOutboundVolumeV54(){return spareVolumeV54()+toolVolumeV54()+portableEquipmentVolumeV54()}
function dynamicResourceVolumeV54(resources=ensureDynamicCargoV52().resources){return Object.entries(resources||{}).reduce((l,[k,v])=>l+resourceVolumeV54(k,v),0)}
function dynamicAssetSpaceV54(ids=ensureDynamicCargoV52().assets){return (ids||[]).reduce((o,id)=>{const s=assetSpaceV54(id);o.volumeL+=s.volumeL;o.anchors+=s.anchors;return o},{volumeL:0,anchors:0})}
const _dynamicCargoSnapshotV54=dynamicCargoSnapshotV52;
dynamicCargoSnapshotV52=function(){const kg=_dynamicCargoSnapshotV54(),g=fieldCargoGeometryV54(),asset=dynamicAssetSpaceV54(),fixedVolume=fixedOutboundVolumeV54(),resourceVolume=dynamicResourceVolumeV54(),usedVolume=fixedVolume+resourceVolume+asset.volumeL;return {...kg,volumeL:g.volumeL,usedVolumeL:usedVolume,freeVolumeL:Math.max(0,g.volumeL-usedVolume),volumeOk:usedVolume<=g.volumeL+1e-6,anchors:g.anchors,anchorUsed:asset.anchors,anchorFree:Math.max(0,g.anchors-asset.anchors),anchorOk:asset.anchors<=g.anchors,seats:g.seats,geometry:g,ok:kg.ok&&usedVolume<=g.volumeL+1e-6&&asset.anchors<=g.anchors}}
function pickupByGeometryV54(rem,freeKg,freeL){const gain={};for(const k of RES_ORDER){const av=Math.max(0,+rem?.[k]||0),w=RES_WEIGHT[k]||1,v=FIELD_RESOURCE_VOLUME_L_V54[k]||Math.max(.1,w*1.15);if(av<=0||freeKg<=.05||freeL<=.05)continue;const max=Math.max(0,Math.floor(Math.min(freeKg/w,freeL/v))),take=Math.min(av,max);if(take<=0)continue;gain[k]=take;freeKg-=take*w;freeL-=take*v}return {gain,freeKg,freeL}}
function dynamicCargoForecastV54(){
 const capacity=fieldCargoCapacityV50(),g=fieldCargoGeometryV54(),fixedKg=fixedOutboundMassV52(),fixedL=fixedOutboundVolumeV54(),rows=[],issues=[];let resources={},assets=[],kg=fixedKg,l=fixedL,anchors=0,maxKg=kg,maxL=l,maxAnchors=0;
 if(kg>capacity+1e-6)issues.push(`出發固定裝載超重 ${(kg-capacity).toFixed(1)} kg`);if(l>g.volumeL+1e-6)issues.push(`出發固定裝載體積超出 ${(l-g.volumeL).toFixed(0)} L`);
 for(const stop of ensureItineraryV27().stops){const name=mapLoc(stop.location)?.name||stop.location,beforeKg=kg,beforeL=l,events=[];const passengers=rescuePassengerCountV52(stop);
  if(passengers&&Number.isFinite(g.seats)){const seats=fieldTeamSizeV43()+passengers;events.push(`救援乘員：座位 ${seats}/${g.seats}`);if(seats>g.seats)issues.push(`${name}：救援後需要 ${seats} 席，但車艙只有 ${g.seats} 席`)}
  if(stop.action==='search'){const sim=pickupByGeometryV54(state.locations?.[stop.location]?.remaining||{},Math.max(0,capacity-kg),Math.max(0,g.volumeL-l));const addKg=dynamicResourceMassV52(sim.gain),addL=dynamicResourceVolumeV54(sim.gain);for(const [k,v] of Object.entries(sim.gain))resources[k]=(resources[k]||0)+v;kg+=addKg;l+=addL;if(addKg>0)events.push(`搜索 +${addKg.toFixed(1)}kg / ${addL.toFixed(0)}L`)}
  if(stop.action==='asset'){const a=assetAtStopV46(stop);if(a&&!assets.includes(a.id)){const st=state.assets?.[a.id],allowed=!st||st.owner==='world'||st.owner==='player';if(allowed){const sp=assetSpaceV54(a.id),kgFail=kg+a.weight>capacity+1e-6,lFail=l+sp.volumeL>g.volumeL+1e-6,aFail=anchors+sp.anchors>g.anchors;if(kgFail)issues.push(`${name}：${a.name}重量超出剩餘載重`);if(lFail)issues.push(`${name}：${a.name}需要 ${sp.volumeL}L 空間，但貨艙體積不足`);if(aFail)issues.push(`${name}：${a.name}需要 ${sp.anchors} 個固定點，但只剩 ${Math.max(0,g.anchors-anchors)} 個`);if(!kgFail&&!lFail&&!aFail){assets.push(a.id);kg+=a.weight;l+=sp.volumeL;anchors+=sp.anchors;events.push(`${a.name} +${a.weight}kg / ${sp.volumeL}L / 固定點 ${sp.anchors}`)}}}}
  maxKg=Math.max(maxKg,kg);maxL=Math.max(maxL,l);maxAnchors=Math.max(maxAnchors,anchors);rows.push({stop,name,beforeKg,beforeL,afterKg:kg,afterL:l,anchors,events,freeKg:Math.max(0,capacity-kg),freeL:Math.max(0,g.volumeL-l),anchorFree:Math.max(0,g.anchors-anchors)})
 }
 return {capacity,volumeL:g.volumeL,anchors:g.anchors,seats:g.seats,geometry:g,fixed:fixedKg,fixedVolumeL:fixedL,resources,assets,rows,maxUsed:maxKg,maxVolumeL:maxL,maxAnchors,endUsed:kg,endVolumeL:l,endFree:Math.max(0,capacity-kg),endFreeVolumeL:Math.max(0,g.volumeL-l),endAnchorFree:Math.max(0,g.anchors-anchors),issues:[...new Set(issues)],ok:issues.length===0}
}
const _fieldTeamValidationV54=fieldTeamValidationV43;
fieldTeamValidationV43=function(e){const v=_fieldTeamValidationV54(e),geo=dynamicCargoForecastV54(),issues=[...v.issues,...geo.issues];return {...v,cargoFlow:geo,cargoGeometry:geo,ok:issues.length===0,issues:[...new Set(issues)]}};
const _collectStopLootV54=collectStopLootV27;
collectStopLootV27=function(loc){const t=ensureFieldTeamV43();if(!t.active)return _collectStopLootV54(loc);const c=ensureDynamicCargoV52(),snap=dynamicCargoSnapshotV52(),rem=state.locations[loc.id].remaining,sim=pickupByGeometryV54(rem,snap.free,snap.freeVolumeL),gain=sim.gain;for(const [k,v] of Object.entries(gain)){rem[k]-=v;c.resources[k]=(c.resources[k]||0)+v}state.locations[loc.id].searched=true;state.intel[loc.id]={day:state.day,verifiedDay:state.day,summary:summarizeRemaining(rem),source:'行程實地搜索',confidence:100};discoverAssetsAt(loc.id);tutorialWaterGain(gain);const kg=dynamicResourceMassV52(gain),vol=dynamicResourceVolumeV54(gain),after=dynamicCargoSnapshotV52();c.history.push({day:state.day,location:loc.id,type:'search',kg,volumeL:vol,gain:{...gain},usedKg:after.used,usedVolumeL:after.usedVolumeL});log(`${loc.name}行程搜索：${Object.entries(gain).map(([k,v])=>`${RES_LABELS[k]||k}+${v}`).join('、')||'貨艙重量／體積已無法再裝'}｜${after.used.toFixed(1)}kg / ${after.usedVolumeL.toFixed(0)}L。`,'good')};
loadAssetIntoDynamicCargoV52=function(stop){const t=ensureFieldTeamV43();if(!t.active||stop?.action!=='asset'||stop._dynamicAssetLoadedV52)return true;const a=assetAtStopV46(stop);if(!a)return true;const st=state.assets?.[a.id];if(st&&st.owner!=='world'&&st.owner!=='player')return false;const c=ensureDynamicCargoV52(),snap=dynamicCargoSnapshotV52(),sp=assetSpaceV54(a.id);if(c.assets.includes(a.id))return true;if(snap.free+1e-6<a.weight)return pauseItineraryV27(`${a.name}需要 ${a.weight}kg，但只剩 ${snap.free.toFixed(1)}kg 載重`),false;if(snap.freeVolumeL+1e-6<sp.volumeL)return pauseItineraryV27(`${a.name}需要 ${sp.volumeL}L 貨艙體積，但只剩 ${snap.freeVolumeL.toFixed(0)}L`),false;if(snap.anchorFree<sp.anchors)return pauseItineraryV27(`${a.name}需要 ${sp.anchors} 個固定點，但只剩 ${snap.anchorFree}`),false;c.assets.push(a.id);if(st){st.inTransit=true;st.location=ensureItineraryV27().current||stop.location}stop._dynamicAssetLoadedV52=true;const after=dynamicCargoSnapshotV52();c.history.push({day:state.day,location:stop.location,type:'asset',assetId:a.id,kg:a.weight,volumeL:sp.volumeL,anchors:sp.anchors,usedKg:after.used,usedVolumeL:after.usedVolumeL});log(`${a.name}已固定進貨艙：${a.weight}kg / ${sp.volumeL}L / 固定點 ${sp.anchors}；目前固定點 ${after.anchorUsed}/${after.anchors}。`,'major');return true};
function cargoGeometryHtmlV54(){const t=ensureFieldTeamV43(),active=t.active,s=active?dynamicCargoSnapshotV52():dynamicCargoForecastV54(),usedKg=active?s.used:s.maxUsed,usedL=active?s.usedVolumeL:s.maxVolumeL,usedA=active?s.anchorUsed:s.maxAnchors,seats=Number.isFinite(s.seats)?s.seats:'—';const rows=active?(ensureDynamicCargoV52().history||[]).slice(-5).map(r=>`<div class="cargo-geo-row"><b>${mapLoc(r.location)?.name||r.location}</b><span>${r.kg?.toFixed?.(1)||0}kg · ${(r.volumeL||0).toFixed(0)}L${r.anchors?` · 固定點 ${r.anchors}`:''}</span></div>`).join(''):(s.rows||[]).map((r,i)=>`<div class="cargo-geo-row"><b>${i+1}. ${r.name}</b><span>${r.afterKg.toFixed(1)}kg · ${r.afterL.toFixed(0)}L · 固定點 ${r.anchors}/${s.anchors}</span><small>${r.events.join(' · ')||'無新增貨物'}</small></div>`).join('');return `<div class="cargo-geometry-box ${s.ok===false?'blocked':''}"><div class="field-role-head"><div><span>CARGO GEOMETRY</span><h4>貨艙空間／固定點</h4></div><b>${s.geometry?.label||'外勤裝載'}</b></div><div class="cargo-geo-metrics"><span>重量 <b>${usedKg.toFixed(1)} / ${s.capacity.toFixed(1)} kg</b></span><span>體積 <b>${usedL.toFixed(0)} / ${s.volumeL.toFixed(0)} L</b></span><span>固定點 <b>${usedA} / ${s.anchors}</b></span><span>座艙 <b>${fieldTeamSizeV43()} / ${seats} 席</b></span></div><p class="muted">重量、體積、固定點與座位分開計算；任一項不足都不能假設「還有公斤數就塞得下」。</p><div class="cargo-geo-list">${rows||'<p class="muted">目前沒有貨艙事件。</p>'}</div>${s.issues?.length?`<div class="field-team-issues">${s.issues.map(x=>`<p>${x}</p>`).join('')}</div>`:''}</div>`}
const _subtaskPlannerHtmlV54=subtaskPlannerHtmlV46;
subtaskPlannerHtmlV46=function(){const html=_subtaskPlannerHtmlV54(),box=cargoGeometryHtmlV54();return html.replace('<div class="parallel-stop-list">',box+'<div class="parallel-stop-list">')};
