function renderActionCenter(){
 const loc=actionTarget(); state.mapPlanner.target=loc.id; state.mapPlanner.routeMode=actionFlow.routeMode;
 $('actionSteps').innerHTML=actionStepLabels().map((x,i)=>`<span class="action-step ${i+1===actionFlow.step?'active':i+1<actionFlow.step?'done':''}">${i+1} ${x}</span>`).join('');
 let body='';
 const guide=state.onboarding?.enabled&&!state.onboarding.completed?`<div class="action-guide"><b>${tutorialCopy().k} · ${tutorialCopy().title}</b><span>${tutorialCopy().text}</span></div>`:'';
 if(actionFlow.step===1){body=`<div class="action-grid"><div class="action-pane"><h3>選擇目標</h3><div class="action-targets">${locations.filter(l=>l.id!=='base').map(l=>`<button class="action-target ${l.id===loc.id?'selected':''}" data-action-target="${l.id}"><img src="${locationThumbArt(l.id)}"><span><b>${l.name}</b><small>${locationTags(l.id).join(' · ')}</small><small>${sceneStatusTags(l.id).join(' · ')||'無特殊狀態'}</small></span></button>`).join('')}</div></div><div class="action-pane"><h3>目前判讀</h3><div class="location-scene${sceneClass(loc.id)}"><img class="scene-base" src="${locationArt(loc.id)}">${sceneOverlayHtml(loc.id)}${districtHistoryHtml(loc.id)}</div><p>${loc.desc}</p>${sceneStatusHtml(loc.id)}</div></div>`}
 if(actionFlow.step===2){body=`<div class="action-grid"><div class="action-pane"><h3>${loc.name}｜已知情報</h3>${actionIntelHtml(loc)}</div><div class="action-pane"><h3>決策提示</h3><p>情報不是世界真相。舊情報可能造成錯誤路線或錯誤裝載；沒有情報也不代表不能出發，只代表偵察成本更高。</p><div class="planner-facts"><span>地點風險 <b>${loc.risk}/4</b></span><span>搜索時間 <b>${timeCostFor(loc)}h</b></span><span>大型資產 <b>${discoveredAssetsAt(loc.id).length}</b></span><span>玩家標記 <b>${notesAt(loc.id).length}</b></span></div></div></div>`}
 if(actionFlow.step===3){const fast=computeMapRoute(loc.id,'fastest'),safe=computeMapRoute(loc.id,'safe');const row=(r,m,n)=>`<button class="route-option ${actionFlow.routeMode===m?'selected':''}" data-action-route="${m}"><span>${n}</span><b>${r.distance} km · 熱 ${routeHeatLabel(r.heat)}</b><small>${r.path.map(id=>mapLoc(id)?.name).join(' → ')}</small><small>${state.day>=30?`冷卻 ${r.cooling}kWh · `:''}${state.gear.vehicle?`燃料 ${r.fuel}L`:''}</small></button>`;body=`<div class="action-grid"><div class="action-pane"><h3>比較路線</h3><div class="action-route-picks">${row(fast,'fastest','最快路線')}${row(safe,'safe','低熱路線')}</div></div><div class="action-pane"><h3>路線地圖</h3><p>選定路線會直接改變下一步的時間、冷卻與燃料估算。</p><div class="planner-facts"><span>中央冷卻覆蓋 <b>${Math.round(coolingReach())}%</b></span><span>外部冷站 <b>${state.coldStations.length}</b></span><span>已知道路情報 <b>${Object.keys(state.roadIntel||{}).length}</b></span></div></div></div>`}
 if(actionFlow.step===4){const modes=availableTransportModes(),assets=expeditionAssetOptions(loc.id);body=`<div class="action-grid"><div class="action-pane"><h3>裝載</h3><div class="action-loadout"><label>交通方式<select id="actionMode">${modes.map(m=>`<option value="${m[0]}" ${m[0]===actionFlow.mode?'selected':''}>${m[1]} · ${m[2]}kg</option>`).join('')}</select></label><label>攜帶飲水<input id="actionWater" type="number" min="0" step="0.5" value="${actionFlow.water}"></label><label>攜帶電池<input id="actionBattery" type="number" min="0" step="1" value="${actionFlow.battery}"></label><label>回收優先<select id="actionPriority">${['water','food','medicine','battery','parts','coolant','data'].map(k=>`<option value="${k}" ${k===actionFlow.priority?'selected':''}>${RES_LABELS[k]||k}</option>`).join('')}</select></label><label>大型設備<select id="actionAsset"><option value="">不指定</option>${assets.map(a=>`<option value="${a.id}" ${a.id===actionFlow.assetId?'selected':''}>${a.name} · ${a.weight}kg</option>`).join('')}</select></label><label class="checkline"><input id="actionToolkit" type="checkbox" ${actionFlow.toolkit?'checked':''} ${state.gear.toolkit?'':'disabled'}>遠征工具箱</label></div></div><div class="action-pane" id="actionLoadEstimate"></div></div>`}
 if(actionFlow.step===5){const e=expeditionEstimate(loc,actionFlow.mode,actionFlow.water,actionFlow.battery,actionFlow.toolkit,actionFlow.assetId),issues=actionIssues(loc,e);body=`<div class="action-confirm"><div class="action-pane"><h3>行動確認</h3><div class="action-summary"><div><span>目的地</span><b>${loc.name}</b></div><div><span>路線</span><b>${actionFlow.routeMode==='safe'?'低熱':'最快'}</b></div><div><span>交通</span><b>${actionFlow.mode==='vehicle'?'工程車':actionFlow.mode==='cart'?'推車':'徒手'}</b></div><div><span>時間</span><b>${e.total}h</b></div><div><span>往返距離</span><b>${e.dist*2}km</b></div><div><span>回收空間</span><b>${e.returnCap}kg</b></div><div><span>飲水</span><b>${actionFlow.water}/${e.waterNeed}L</b></div><div><span>電池</span><b>${actionFlow.battery}/${e.batteryNeed}kWh</b></div><div><span>燃料</span><b>${e.fuelNeed}L</b></div></div></div><div class="action-pane"><h3>出發判定</h3>${issues.length?`<div class="action-warning">${issues.join('；')}</div>`:'<div class="action-ready">所有已知條件允許出發。途中仍可能因情報失真或設備狀況出現事件。</div>'}<p>${actionIntelHtml(loc)}</p></div></div>`}
 $('actionCenterContent').innerHTML=guide+body+`<div class="action-footer"><button id="actionPrev" class="secondary" ${actionFlow.step===1?'disabled':''}>上一步</button><div>${actionFlow.step<5?'<button id="actionNext">下一步</button>':'<button id="actionLaunch">出發</button>'}</div></div>`;
 document.querySelectorAll('[data-action-target]').forEach(b=>b.onclick=()=>{actionFlow.target=b.dataset.actionTarget;actionFlow.assetId='';renderActionCenter()});
 document.querySelectorAll('[data-action-route]').forEach(b=>b.onclick=()=>{actionFlow.routeMode=b.dataset.actionRoute;state.mapPlanner.routeMode=actionFlow.routeMode;renderActionCenter()});
 if($('actionPrev'))$('actionPrev').onclick=()=>{actionFlow.step=Math.max(1,actionFlow.step-1);renderActionCenter()};
 if($('actionNext'))$('actionNext').onclick=()=>{actionFlow.step=Math.min(5,actionFlow.step+1);renderActionCenter()};
 ['actionMode','actionWater','actionBattery','actionPriority','actionAsset','actionToolkit'].forEach(id=>{if($(id))$(id).onchange=syncActionLoadout});if($('actionWater'))$('actionWater').oninput=syncActionLoadout;if($('actionBattery'))$('actionBattery').oninput=syncActionLoadout;
 if($('actionLaunch'))$('actionLaunch').onclick=launchActionCenter;
 if(actionFlow.step===4)syncActionLoadout(false);
}
function syncActionLoadout(rerender=true){if($('actionMode'))actionFlow.mode=$('actionMode').value;if($('actionWater'))actionFlow.water=Math.max(0,+$('actionWater').value||0);if($('actionBattery'))actionFlow.battery=Math.max(0,+$('actionBattery').value||0);if($('actionPriority'))actionFlow.priority=$('actionPriority').value;if($('actionAsset'))actionFlow.assetId=$('actionAsset').value;if($('actionToolkit'))actionFlow.toolkit=$('actionToolkit').checked;const loc=actionTarget(),e=expeditionEstimate(loc,actionFlow.mode,actionFlow.water,actionFlow.battery,actionFlow.toolkit,actionFlow.assetId),issues=actionIssues(loc,e);if($('actionLoadEstimate'))$('actionLoadEstimate').innerHTML=`<h3>即時估算</h3><div class="estimate-list"><div><span>總時間</span><b>${e.total}h</b></div><div><span>載重</span><b>${e.supplyWeight+e.assetWeight}/${e.cap}kg</b></div><div><span>回收空間</span><b>${e.returnCap}kg</b></div><div><span>最低飲水</span><b>${e.waterNeed}L</b></div><div><span>冷卻</span><b>${e.batteryNeed}kWh</b></div><div><span>燃料</span><b>${e.fuelNeed}L</b></div></div>${issues.length?`<div class="action-warning">${issues.join('；')}</div>`:'<div class="action-ready">裝載可行</div>'}`}
