const coreStages=[
 {id:'scout',name:'1. 核心偵察',labor:24,cost:{data:2,battery:2},req:()=>state.day>=45&&state.knownCore&&state.research.core,why:'確認核心位置、尺寸、溫度與拆離接口。'},
 {id:'route',name:'2. 清理重運路線',labor:40,cost:{fuel:6,parts:6},req:()=>state.gear.vehicle&&state.gear.toolkit,why:'清除道路阻塞並標記承重風險。'},
 {id:'relay',name:'3. 建立中繼冷站鏈',labor:48,cost:{battery:8,parts:8,coolant:5},req:()=>state.coldStations.length>=2&&state.research.coldStation,why:'讓拆離與重運隊能在 100°C 永晝中工作。'},
 {id:'detach',name:'4. 拆離冷源核心',labor:56,cost:{battery:6,parts:10,coolant:4},req:()=>state.installed.lift&&state.installed.compressors>=1,why:'斷開核心固定件、冷卻接口與高壓管線。'},
 {id:'haul',name:'5. 重型運輸',labor:64,cost:{fuel:10,battery:8,parts:4},req:()=>state.logistics.heavyReady&&state.gear.vehicle&&state.vehicle.condition>=45,why:'把核心本體從實驗設施運到中央通風站。'},
 {id:'lift',name:'6. 吊裝定位',labor:48,cost:{parts:10,battery:4},req:()=>state.installed.lift&&state.base.ventilation>=2,why:'將核心固定到中央站主機座並完成抗震鎖定。'},
 {id:'power',name:'7. 主配電整合',labor:60,cost:{battery:12,parts:12},req:()=>state.installed.inverter&&state.installed.generator&&state.base.powerKW>=8,why:'建立核心獨立供電、保護與緊急旁路。'},
 {id:'loop',name:'8. 冷卻迴路接管',labor:72,cost:{coolant:16,parts:14,battery:6},req:()=>state.installed.compressors>=2&&state.installed.chiller&&state.installed.pump,why:'完成壓縮機、冰水機、消防泵與核心的封閉循環。'},
 {id:'pressure',name:'9. 壓力與負載測試',labor:40,cost:{battery:12,parts:6},req:()=>state.base.condition>=65&&state.base.ventilation>=2,why:'逐步加壓、查漏、驗證配電與排熱。'},
 {id:'stability',name:'10. 72 小時穩定運轉',labor:0,cost:{},req:()=>state.base.condition>=60&&state.resources.water>=dailyWaterNeed()*2,why:'連續三天維持核心、冷卻、水務與人口負載，才算真正重啟。'}
];
function coreStage(){return coreStages[Math.min(state.coreProject.stage,coreStages.length-1)]}
function coreDone(){return state.coreProject.stage>=coreStages.length}
function coreCrew(){return state.workforce.core||0}
function coreEfficiency(){let e=1-state.fatigue/140;if(state.ration.water<2.5)e-=.1;if(state.ration.food<1)e-=.08;if(state.base.condition<60)e-=.15;e+=(state.training.hvac+state.training.electric)*.02;return clamp(e,.3,1.35)}
function coreDailyHours(){return Math.round(coreCrew()*4*coreEfficiency()*10)/10}
function coreReqText(stage){const missing=[];if(!stage.req())missing.push('設備／前置條件未滿足');for(const [k,v] of Object.entries(stage.cost||{})){if((state.resources[k]||0)<v)missing.push(`${RES_LABELS[k]||k} 缺 ${Math.ceil(v-(state.resources[k]||0))}`)}return missing.join('、')}
function startCoreStage(){if(state.base.core||coreDone())return toast('冷源核心已完成');const st=coreStage();if(state.coreProject.active)return toast('此階段已在施工');if(!st.req())return toast('前置條件未滿足');if(!hasCost(st.cost))return toast('材料不足');if(st.id==='stability'){state.coreProject.active=true;state.coreProject.progress=0;state.coreProject.stability=0;log('開始 72 小時穩定運轉驗收。任何重大冷卻或供水問題都會中斷計時。','major');openCoreProject();return}pay(st.cost);state.coreProject.active=true;state.coreProject.progress=0;state.coreProject.paid=true;log(`核心工程開始：${st.name}。已投入本階段材料，接下來需要 ${st.labor} 人時。`,'major');openCoreProject();render()}
function completeCoreStage(){const st=coreStage();state.coreProject.completed.push(st.id);state.coreProject.stage++;state.coreProject.active=false;state.coreProject.progress=0;state.coreProject.paid=false;log(`核心工程完成：${st.name}。`,'good');if(coreDone()){state.base.core=true;state.base.coolingCapacity=150;state.base.ventCapacity=140;state.base.condition=Math.max(state.base.condition,90);log('冷源核心通過連續穩定運轉。中央通風站正式進入城市級冷卻模式。','major');toast('冷源核心完整重啟')}}
function coreProjectTick(){if(!state.coreProject.active||state.base.core||coreDone())return;const st=coreStage();if(st.id==='stability'){const stable=state.base.condition>=60&&state.resources.water>=dailyWaterNeed()&&coolingLoadPct()<=105;if(stable){state.coreProject.stability++;state.coreProject.progress=state.coreProject.stability;log(`核心穩定驗收：第 ${state.coreProject.stability}/3 天維持正常。`,'good');if(state.coreProject.stability>=3)completeCoreStage()}else{state.coreProject.stability=0;state.coreProject.progress=0;log('核心穩定驗收中斷：冷卻負載、供水或設備狀況未達標，72 小時計時重新開始。','bad')}return}const hrs=coreDailyHours();if(hrs<=0){if(state.day%2===0)log(`核心工程「${st.name}」停工：沒有分配核心工程隊。`,'bad');return}state.coreProject.progress+=hrs;state.coreProject.lastWorkDay=state.day;log(`核心工程「${st.name}」今日投入 ${hrs} 人時，累計 ${Math.floor(state.coreProject.progress)}/${st.labor}。`,'');if(state.coreProject.progress>=st.labor)completeCoreStage()}
function openCoreProject(){const cp=state.coreProject;const done=coreDone()||state.base.core;const st=done?null:coreStage();const phaseHtml=coreStages.map((x,i)=>{let cls=i<cp.stage?'core-step done':i===cp.stage?'core-step current':'core-step';let sub=i<cp.stage?'完成':i===cp.stage?(cp.active?'施工中':'待啟動'):'未開始';return `<div class="${cls}"><b>${x.name}</b><span>${sub}</span></div>`}).join('');let action='';if(done){action='<div class="core-finish"><h3>城市級冷卻已完成</h3><p>核心通過最終穩定驗收。接下來要維持人口、設備與資源到 Day 60。</p></div>'}else{const need=coreReqText(st);const progress=st.id==='stability'?`${cp.stability}/3 天`:`${Math.floor(cp.progress)}/${st.labor} 人時`;const eta=st.labor>0&&coreDailyHours()>0?Math.ceil(Math.max(0,st.labor-cp.progress)/coreDailyHours())+' 天':'—';action=`<div class="project-focus"><h3>${st.name}</h3><p>${st.why}</p><div class="route-summary"><div><span>進度</span><b>${progress}</b></div><div><span>核心工程隊</span><b>${coreCrew()} 人</b></div><div><span>今日預估</span><b>${st.id==='stability'?'自動驗收':coreDailyHours()+' 人時'}</b></div><div><span>估計剩餘</span><b>${st.id==='stability'?Math.max(0,3-cp.stability)+' 天':eta}</b></div></div><p><b>階段投入：</b>${Object.keys(st.cost).length?Object.entries(st.cost).map(([k,v])=>`${RES_LABELS[k]||k} ${v}`).join('、'):'無一次性材料'}</p>${need?`<p class="bad-text">目前缺少：${need}</p>`:''}<div class="dialog-actions"><button id="startCoreStage" ${cp.active||need?'disabled':''}>${cp.active?'施工中':'啟動此階段'}</button><button id="openCoreStaff" class="secondary">調整工程人力</button></div></div>`} $('coreProjectContent').innerHTML=`<div class="project-banner"><div><span>Day ${state.day}</span><b>${done?'10/10':cp.stage+'/10'} 階段完成</b></div><div><span>Day 60 前剩餘</span><b>${Math.max(0,60-state.day)} 天</b></div></div><div class="core-timeline">${phaseHtml}</div>${action}`;if(!$('coreProjectDialog').open)$('coreProjectDialog').showModal();if($('startCoreStage'))$('startCoreStage').onclick=startCoreStage;if($('openCoreStaff'))$('openCoreStaff').onclick=()=>{ $('coreProjectDialog').close();openBaseMgmt()}}
function nightHours(d){if(d<=7)return 8;if(d<=14)return 6;if(d<=21)return 4;if(d<=29)return 2;return 0}
function phaseBand(d=state.day){if(d<=7)return {id:'adapt',name:'適應期',npcSearch:2,take:1.0};if(d<=14)return {id:'logistics',name:'物流期',npcSearch:2,take:1.15};if(d<=21)return {id:'pressure',name:'壓縮期',npcSearch:1,take:1.3};if(d<=29)return {id:'lastNights',name:'最後八夜',npcSearch:1,take:1.5};if(d<=44)return {id:'endless',name:'永晝重建',npcSearch:1,take:1.25};return {id:'endgame',name:'核心工程期',npcSearch:1,take:1.15}}
function foodDays(){return Math.max(0,Math.floor(state.resources.food/Math.max(1,dailyFoodNeed())))}
function coreSchedulePressure(){if(state.base.core)return 0;if(state.day<45)return 0;const expected=state.day<50?1:state.day<55?4:state.day<58?7:9;return Math.max(0,expected-state.coreProject.stage)}
