function openActionCenter(prefill=''){const tutorialTarget=tutorialStage()===1?'store':tutorialStage()===2?'hardware':tutorialStage()===3?'school':'';const target=prefill||tutorialTarget||state.mapPlanner?.target||'homes';actionFlow={step:1,target,mode:availableTransportModes().slice(-1)[0][0],water:Math.min(state.resources.water,state.day>=30?4:2),battery:Math.min(state.resources.battery,state.day>=30?8:2),priority:'water',assetId:'',toolkit:!!state.gear.toolkit,routeMode:state.mapPlanner?.routeMode||'fastest'};state.mapPlanner.target=target;state.mapPlanner.routeMode=actionFlow.routeMode;renderActionCenter();if(!$('actionCenterDialog').open)$('actionCenterDialog').showModal()}
function launchActionCenter(){if(state.onboarding?.enabled)state.onboarding.introSeen=true;const loc=actionTarget(),e=expeditionEstimate(loc,actionFlow.mode,actionFlow.water,actionFlow.battery,actionFlow.toolkit,actionFlow.assetId),issues=actionIssues(loc,e);if(issues.length)return toast(issues[0]);const trip={locId:loc.id,mode:actionFlow.mode,water:actionFlow.water,battery:actionFlow.battery,priority:actionFlow.priority,useToolkit:actionFlow.toolkit,assetId:actionFlow.assetId,estimate:e};$('actionCenterDialog').close();startTrip(trip)}
function startTrip(trip){const incident=pickExpeditionIncident(trip);if(incident){state.expedition.pending={...trip,incident};state.expedition.incidents++;openExpeditionIncident();saveGame(false);return}finalizeExpedition(trip,{time:0,battery:0,fuel:0,cargoFactor:1,vehicleDamage:0})}
function openCityOps(){if(!$('cityOpsDialog')){openIntel();return}$('cityOpsDialog').showModal()}

function openExpedition(prefill=''){
 const modes=availableTransportModes(),target=prefill||locations.find(l=>l.id!=='base')?.id||'homes';
 $('expeditionContent').innerHTML=`<div class="expedition-visual" id="expVisual"></div><div class="expedition-grid"><div class="expedition-form">
 <label>目的地<select id="expTarget">${locations.filter(l=>l.id!=='base').map(l=>`<option value="${l.id}" ${l.id===target?'selected':''}>${l.name}</option>`).join('')}</select></label>
 <label>交通方式<select id="expMode">${modes.map(m=>`<option value="${m[0]}">${m[1]} · ${m[2]}kg</option>`).join('')}</select></label>
 <label>攜帶飲水<input id="expWater" type="number" min="0" step="0.5" value="2"></label>
 <label>攜帶電池<input id="expBattery" type="number" min="0" step="1" value="${state.day>=30?8:2}"></label>
 <label>回收優先<select id="expPriority">${['water','food','medicine','battery','parts','coolant','data'].map(k=>`<option value="${k}">${RES_LABELS[k]||k}</option>`).join('')}</select></label>
 <label>大型設備<select id="expAsset"><option value="">不指定</option></select></label>
 <label class="checkline"><input id="expToolkit" type="checkbox" ${state.gear.toolkit?'':'disabled'}>攜帶遠征工具箱 ${state.gear.toolkit?'':'（尚未製作）'}</label>
 </div><div id="expEstimate" class="expedition-estimate"></div></div><div class="dialog-actions"><button id="runExpedition">執行遠征</button></div>`;
 if(!$('expeditionDialog').open)$('expeditionDialog').showModal();
 const refreshAssets=()=>{const id=$('expTarget').value,opts=expeditionAssetOptions(id);$('expAsset').innerHTML='<option value="">不指定</option>'+opts.map(a=>{const st=state.assets[a.id];return `<option value="${a.id}">${a.name} · ${a.weight}kg · ${ownerLabel(st.owner)}</option>`}).join('')};
 const update=()=>{const loc=locations.find(l=>l.id===$('expTarget').value),mode=$('expMode').value,water=Math.max(0,+$('expWater').value||0),battery=Math.max(0,+$('expBattery').value||0),kit=$('expToolkit').checked,assetId=$('expAsset').value,e=expeditionEstimate(loc,mode,water,battery,kit,assetId);let issues=[];if(water>state.resources.water)issues.push('攜帶水超過庫存');if(battery>state.resources.battery)issues.push('攜帶電池超過庫存');if(water<e.waterNeed)issues.push(`建議至少 ${e.waterNeed}L 水`);if(state.day>=30&&battery<e.batteryNeed)issues.push(`永晝至少配置 ${e.batteryNeed}kWh 電池`);if(mode==='vehicle'&&state.resources.fuel<e.fuelNeed)issues.push(`燃料不足，需要 ${e.fuelNeed}L`);if(e.supplyWeight+e.assetWeight>e.cap)issues.push('補給＋大型設備已超過載重');if(e.asset){const st=state.assets[e.asset.id];if(st.owner!=='world'&&st.owner!=='player')issues.push(`設備目前由${ownerLabel(st.owner)}控制`);if(e.asset.need==='vehicle'&&mode!=='vehicle')issues.push('此設備必須使用工程車');if(e.asset.need==='cart'&&mode==='foot')issues.push('此設備至少需要推車')}if(state.day<30&&state.phase!=='night')issues.push('目前是白晝');if(state.day<30&&state.hoursLeft<e.total)issues.push(`夜晚只剩 ${state.hoursLeft}h`);if(state.day>=30&&!state.gear.coolingPack&&!state.base.core)issues.push('永晝缺少主動冷卻');
 preloadScene(loc.id);$('expVisual').innerHTML=`<div class="expedition-scene${sceneClass(loc.id)}"><img class="scene-base" src="${locationArt(loc.id)}" alt="${loc.name}" decoding="async">${sceneOverlayHtml(loc.id)}${districtHistoryHtml(loc.id)}<span class="scene-quality">${sceneBadge(loc.id)} · ${sceneMode().toUpperCase()}</span></div><div><b>${loc.name}</b><span>${locationTags(loc.id).join(' · ')}</span>${sceneStatusHtml(loc.id)}<small>${loc.desc}</small></div>`;
 $('expEstimate').innerHTML=`<h3>遠征預估</h3><div class="estimate-list"><div><span>往返距離</span><b>${e.dist*2} km</b></div><div><span>路線策略</span><b>${state.mapPlanner?.routeMode==='safe'?'低熱':'最快'}</b></div><div><span>總時間</span><b>${e.total} h</b></div><div><span>載重</span><b>${e.supplyWeight+e.assetWeight} / ${e.cap} kg</b></div><div><span>回收空間</span><b>${e.returnCap} kg</b></div><div><span>最低飲水</span><b>${e.waterNeed} L</b></div><div><span>永晝耗電</span><b>${e.batteryNeed} kWh</b></div><div><span>燃料</span><b>${e.fuelNeed} L</b></div></div>${issues.length?`<div class="expedition-warning">${issues.join('；')}</div>`:'<div class="expedition-ready">可以出發</div>'}`;$('runExpedition').disabled=issues.length>0};
 $('expTarget').onchange=()=>{state.mapPlanner.target=$('expTarget').value;refreshAssets();update()};['expMode','expWater','expBattery','expPriority','expAsset','expToolkit'].forEach(id=>$(id).onchange=update);$('expWater').oninput=update;$('expBattery').oninput=update;refreshAssets();update();$('runExpedition').onclick=executeExpedition;
}
function executeExpedition(){
 const loc=locations.find(l=>l.id===$('expTarget').value),mode=$('expMode').value,water=Math.max(0,+$('expWater').value||0),battery=Math.max(0,+$('expBattery').value||0),priority=$('expPriority').value,useToolkit=$('expToolkit').checked,assetId=$('expAsset').value,e=expeditionEstimate(loc,mode,water,battery,useToolkit,assetId);
 if(state.day<30&&(state.phase!=='night'||state.hoursLeft<e.total))return toast('目前無法完成這趟遠征');if(state.day>=30&&!state.gear.coolingPack&&!state.base.core)return toast('永晝缺少主動冷卻');if(state.resources.water<water||state.resources.battery<battery)return toast('補給庫存不足');if(water<e.waterNeed||state.day>=30&&battery<e.batteryNeed)return toast('遠征補給不足');if(mode==='vehicle'&&state.resources.fuel<e.fuelNeed)return toast('燃料不足');if(e.supplyWeight+e.assetWeight>e.cap)return toast('載重超過上限');
 if(e.asset){const st=state.assets[e.asset.id];if(st.owner!=='world'&&st.owner!=='player')return toast('大型設備目前由其他倖存者控制');if(e.asset.need==='vehicle'&&mode!=='vehicle')return toast('大型設備需要工程車');if(e.asset.need==='cart'&&mode==='foot')return toast('大型設備至少需要推車')}
 const trip={locId:loc.id,mode,water,battery,priority,useToolkit,assetId,estimate:e}; $('expeditionDialog').close(); startTrip(trip);
}
