function openRation(){const req=state.pendingRequests.map((r,i)=>`<div class="request"><strong>${r.name} · ${r.people} 人</strong><p>${r.reason}｜目前中央站 ${state.base.population}/${state.base.ventCapacity}</p><div class="dialog-actions"><button data-accept="${i}" ${state.base.ventCapacity-state.base.population<r.people?'disabled':''}>接收入站</button><button data-reject="${i}" class="secondary">拒絕／轉介</button></div></div>`).join('')||'<p class="muted">目前沒有等待處理的遷入申請。</p>';
 $('rationContent').innerHTML=`<div class="ration-grid"><div><h3>每日飲水配給</h3><div class="choice-list">${[[3,'充足','工作效率穩定，耗水最高'],[2.5,'標準','目前建議值'],[2,'緊縮','節水，但長期降低健康與信任'],[1.5,'危機','只適合短期應急']].map(([v,n,d])=>`<div class="choice ${state.ration.water===v?'active':''}"><h3>${n} · ${v}L/人</h3><p>${d}</p><button data-ration="${v}" ${state.ration.water===v?'disabled':''}>採用</button></div>`).join('')}</div></div><div><h3>中央站政策</h3><div class="choice"><h3>入口政策：${intakeLabel()}</h3><p>開放會自動接收有容量的申請；審核由你決定；封閉則會降低外來人口但損害部分信任。</p><div class="dialog-actions"><button data-intake="open">開放</button><button data-intake="review" class="secondary">審核</button><button data-intake="closed" class="secondary">封閉</button></div></div><div class="choice"><h3>目前負載</h3><p>人口 ${state.base.population}/${state.base.ventCapacity}｜冷卻負載 ${state.base.ventCapacity?coolingLoadPct()+'%':'未啟動'}｜每日水 ${dailyWaterNeed()}L</p></div></div></div><h3>遷入申請</h3>${req}`;if(!$('rationDialog').open)$('rationDialog').showModal();document.querySelectorAll('[data-ration]').forEach(b=>b.onclick=()=>{state.ration.water=+b.dataset.ration;log(`中央站飲水配給調整為每人每日 ${state.ration.water}L。`,state.ration.water<2.5?'bad':'good');openRation();render()});document.querySelectorAll('[data-intake]').forEach(b=>b.onclick=()=>{state.ration.intake=b.dataset.intake;log(`中央站入口政策改為：${intakeLabel()}。`);openRation();render()});document.querySelectorAll('[data-accept]').forEach(b=>b.onclick=()=>handleRequest(+b.dataset.accept,true));document.querySelectorAll('[data-reject]').forEach(b=>b.onclick=()=>handleRequest(+b.dataset.reject,false))}
function handleRequest(i,accept){const r=state.pendingRequests[i];if(!r)return;if(accept){if(state.base.population+r.people>state.base.ventCapacity)return toast('中央站容量不足');state.base.population+=r.people;if(r.settlement&&state.settlements[r.settlement])state.settlements[r.settlement].population=Math.max(0,state.settlements[r.settlement].population-r.people);state.base.trust+=1;log(`${r.name}的 ${r.people} 人進入中央通風站。`,'good')}else{state.base.trust-=1;log(`你拒絕了${r.name}的遷入要求。`,'bad')}state.pendingRequests.splice(i,1);openRation();render()}



function transportCapacityFor(mode){if(mode==='vehicle')return state.logistics.heavyReady?1200:state.vehicle.capacityKg;if(mode==='cart')return 80;return 18}
function availableTransportModes(){const out=[['foot','徒手',18]];if(state.gear.cart)out.push(['cart','推車',80]);if(state.gear.vehicle)out.push(['vehicle',state.logistics.heavyReady?'工程車＋液壓平台':'工程車',transportCapacityFor('vehicle')]);return out}
function routeDistanceKm(loc){const r=computeMapRoute(loc.id,state.mapPlanner?.routeMode||'fastest');return r?Math.max(.3,r.distance):Math.max(.3,Math.round(Math.hypot(loc.x-mapLoc('base').x,loc.y-mapLoc('base').y)*.04*10)/10)}
function expeditionEstimate(loc,mode,water,battery,useToolkit,assetId){
 const route=computeMapRoute(loc.id,state.mapPlanner?.routeMode||'fastest'),dist=route?.distance??routeDistanceKm(loc),cap=transportCapacityFor(mode),speed=mode==='vehicle'?24:mode==='cart'?5:4.5;
 const travel=dist*2/speed,toolBonus=useToolkit&&state.gear.toolkit?.45:0;
 const search=Math.max(.5,timeCostFor(loc)-toolBonus),asset=assetId?assetDefs.find(a=>a.id===assetId):null;
 const handling=asset?(asset.need==='vehicle'?1.25:.6):0,total=Math.round((travel+search+handling)*10)/10;
 const waterNeed=Math.round(Math.max(.5,total*.28+loc.risk*.12)*10)/10;
 const routeCooling=route?.cooling??coolingCost(loc),batteryNeed=state.day>=30?Math.max(1,Math.ceil(routeCooling*.72+total*.45+(asset?asset.weight/400:0))):0;
 const fuelNeed=mode==='vehicle'?Math.max(1,Math.ceil(dist*.9+loc.risk*.25+(asset?asset.weight/650:0))):0;
 const supplyWeight=Math.round((water+(battery*.8)+(useToolkit?6:0))*10)/10;
 const assetWeight=asset?asset.weight:0,returnCap=Math.max(0,Math.round((cap-supplyWeight-assetWeight)*10)/10);
 return {dist,cap,total,waterNeed,batteryNeed,fuelNeed,supplyWeight,asset,assetWeight,returnCap,route};
}
function expeditionAssetOptions(locationId){return assetDefs.filter(a=>{const st=state.assets[a.id];return st&&st.discovered&&!st.transported&&st.location===locationId})}

let actionFlow={step:1,target:'homes',mode:'foot',water:2,battery:2,priority:'water',assetId:'',toolkit:false,routeMode:'fastest'};
function actionStepLabels(){return ['目標','情報','路線','裝載','確認']}
function actionTarget(){return locations.find(l=>l.id===actionFlow.target)||locations.find(l=>l.id==='homes')}
function actionIntelHtml(loc){
 const i=state.intel[loc.id], lc=state.locations[loc.id], age=i?state.day-(i.verifiedDay??i.day):null, conf=i?clamp(Math.round((i.confidence??75)-(age||0)*8),10,100):0;
 const roadBits=MAP_ROUTES.filter(([a,b])=>a===loc.id||b===loc.id).map(([a,b])=>{const other=a===loc.id?b:a,ri=roadIntelState(a,b);return `<div class="intel-card ${ri&&roadIntelConfidence(ri)<55?'stale':''}"><b>${loc.name} ↔ ${mapLoc(other)?.name||other}</b><small>${ri?`${ri.status==='blocked'?'封鎖':ri.status==='danger'?'危險':ri.status==='repaired'?'已修復':'可通行'} · 可信 ${roadIntelConfidence(ri)}% · ${ri.source||'未知來源'}`:'沒有道路情報'}</small></div>`}).join('');
 return `<div class="action-intel"><div class="intel-card ${age>2?'stale':''}"><b>地點情報</b><small>${lc.searched?'你已親自搜索過。':i?`${i.summary}｜來源 ${i.source||'未知'}｜${age} 天前｜可信 ${conf}%`:'沒有可靠情報；出發代表同時進行偵察。'}</small></div>${roadBits||'<div class="intel-card"><small>沒有額外道路情報。</small></div>'}${notesAt(loc.id).length?`<div class="intel-card"><b>玩家標記</b><small>${notesAt(loc.id).map(n=>`${noteTypeLabel(n.type)}：${n.text}`).join('；')}</small></div>`:''}</div>`;
}
function actionIssues(loc,e){let issues=[];if(actionFlow.water>state.resources.water)issues.push('攜帶水超過庫存');if(actionFlow.battery>state.resources.battery)issues.push('攜帶電池超過庫存');if(actionFlow.water<e.waterNeed)issues.push(`建議至少 ${e.waterNeed}L 水`);if(state.day>=30&&actionFlow.battery<e.batteryNeed)issues.push(`永晝至少配置 ${e.batteryNeed}kWh 電池`);if(actionFlow.mode==='vehicle'&&state.resources.fuel<e.fuelNeed)issues.push(`燃料不足，需要 ${e.fuelNeed}L`);if(e.supplyWeight+e.assetWeight>e.cap)issues.push('補給＋大型設備已超過載重');if(e.asset){const st=state.assets[e.asset.id];if(st.owner!=='world'&&st.owner!=='player')issues.push(`設備目前由${ownerLabel(st.owner)}控制`);if(e.asset.need==='vehicle'&&actionFlow.mode!=='vehicle')issues.push('此設備必須使用工程車');if(e.asset.need==='cart'&&actionFlow.mode==='foot')issues.push('此設備至少需要推車')}if(state.day<30&&state.phase!=='night')issues.push('目前是白晝');if(state.day<30&&state.hoursLeft<e.total)issues.push(`夜晚只剩 ${state.hoursLeft}h`);if(state.day>=30&&!state.gear.coolingPack&&!state.base.core)issues.push('永晝缺少主動冷卻');return issues}
