function openBrief(){const b=buildBrief();const chains=[['供水','water'],['冷卻／電網','grid'],['人口遷移','migration'],['終局時程','core']].map(([n,k])=>{const l=chainLevel(k),tx=['穩定','前兆','壓力','危機'][l];return `<div class="asset-box"><b>${n}</b><p>${tx}</p></div>`}).join('');const issues=b.issues.length?b.issues.map((x,i)=>`<div class="choice"><h3>${i+1}. ${x.text}</h3><p>${x.act}</p></div>`).join(''):'<div class="core-finish"><h3>沒有迫近的系統性危機</h3><p>可以把時間投入長期物流、情報或終局準備。</p></div>';$('briefContent').innerHTML=`<div class="project-banner"><div><span>Day ${state.day}｜${b.phase}</span><b>整體風險：${b.risk}</b></div><div><span>公共庫存續航</span><b>水 ${b.water} 天｜食物 ${b.food} 天</b></div></div><h3>事件鏈</h3><div class="asset-grid">${chains}</div><h3>建議優先順序</h3><div class="card-list">${issues}</div><p class="muted">這不是任務清單；只是依目前已知狀態推算最可能先失控的系統。</p>`;if(!$('briefDialog').open)$('briefDialog').showModal()}
function makeMorningReport(){if(state.day<30)return;const text=`Day ${state.day} 晨報｜風險 ${riskLabel()}｜人口 ${state.base.population}/${state.base.ventCapacity}｜水 ${daysOfWater()}天｜設備 ${Math.round(state.base.condition)}%｜疲勞 ${Math.round(state.fatigue)}%｜核心 ${state.coreProject.stage}/10`;state.briefs.push(buildBrief());if(state.briefs.length>20)state.briefs.shift();state.morningReports.push(text);if(state.morningReports.length>12)state.morningReports.shift();if(state.day%2===0)log(text,'')}
function openBaseMgmt(){const pop=availableWorkers();const used=assignedWorkers();const jobs=[['water','水務','增加濾水／回收效率'],['cooling','冷卻','提高冷卻運轉效率並培訓空調技能'],['power','電力','增加日常儲能並培訓電力技能'],['medical','醫療','穩定人口與信任並培訓醫療技能'],['logistics','物流','整理回收零件與搬運'],['maintenance','維護','每天恢復中央站設備狀況'],['core','核心工程','投入終局工程人時；受疲勞、配給與技術能力影響']];const rows=jobs.map(([id,n,d])=>`<div class="choice"><h3>${n}</h3><p>${d}｜效率 ${Math.round(workEfficiency(id)*100)}%</p><div class="dialog-actions"><button data-job="${id}" data-d="-1" class="secondary">−</button><b>${state.workforce[id]||0} 人</b><button data-job="${id}" data-d="1">＋</button></div></div>`).join('');$('baseMgmtContent').innerHTML=`<div class="route-summary"><div><span>中央站人口</span><b>${pop}</b></div><div><span>已分配</span><b>${used}</b></div><div><span>休息／未分配</span><b>${Math.max(0,pop-used)}</b></div><div><span>平均疲勞</span><b>${Math.round(state.fatigue)}%</b></div></div><div class="card-list">${rows}</div><h3>技能傳承</h3><p>HVAC ${state.training.hvac.toFixed(1)}/5｜電力 ${state.training.electric.toFixed(1)}/5｜醫療 ${state.training.medical.toFixed(1)}/5</p><h3>基地分區</h3><div class="asset-grid"><div class="asset-box"><b>居住區</b><p>容量 ${state.zones.residential.capacity}</p></div><div class="asset-box"><b>醫療區</b><p>容量 ${state.zones.medical.capacity}</p></div><div class="asset-box"><b>工程區</b><p>容量 ${state.zones.engineering.capacity}</p></div><div class="asset-box"><b>儲藏區</b><p>容量 ${state.zones.storage.capacity}kg</p></div></div><h3>最近晨報</h3>${state.morningReports.slice().reverse().map(x=>`<div class="flow-row">${x}</div>`).join('')||'<p class="muted">Day 30 後開始產生晨報。</p>'}`;if(!$('baseMgmtDialog').open)$('baseMgmtDialog').showModal();document.querySelectorAll('[data-job]').forEach(b=>b.onclick=()=>{const k=b.dataset.job,d=+b.dataset.d;const next=Math.max(0,(state.workforce[k]||0)+d);const others=assignedWorkers()-(state.workforce[k]||0);if(others+next>pop)return toast('沒有足夠可用人力');state.workforce[k]=next;openBaseMgmt();render()})}
function baseDaily(){if(state.day<30)return;if(state.base.ventilation>0){const stress=(coolingLoadPct()/100)+(state.base.condition<60?.45:0);state.base.condition=Math.max(20,state.base.condition-(1.2+stress));if(state.ration.water<2.5){state.base.trust-=state.ration.water<=1.5?2:1;if(state.day%3===0)log('長期緊縮配給讓中央站居民健康與信任下降。','bad')}if(overCapacity()>0){state.base.condition-=Math.min(4,overCapacity()*.25);state.base.trust-=1;if(state.day%2===0)log(`中央站超載 ${overCapacity()} 人，冷卻與用水負荷持續惡化。`,'bad')}if(state.base.condition<45&&Math.random()<.22){state.resources.battery=Math.max(0,state.resources.battery-3);log('中央站泵浦與配電效率惡化，額外消耗 3 kWh 儲能。','bad')}}}
function consumeDaily(){state.resources.water-=dailyWaterNeed();state.resources.food-=dailyFoodNeed();workforceTick();coreProjectTick();privateEconomyTick();if(state.gear.solar&&state.day>=30)state.resources.battery=Math.min(state.base.storageKWh,state.resources.battery+Math.max(2,state.base.powerKW*.5));baseDaily();npcDaily();updateEventChains();makeMorningReport();if(state.base.trust>=7&&state.day%6===0&&state.base.population<state.base.ventCapacity&&state.ration.intake==='open'){state.base.population++;log('一名獨立倖存者加入中央站。','good')}}
function changeRoadWorld(a,b,status,reason){const key=roadKey(a,b);state.roadWorld[key]={status,changedDay:state.day};if(reason)log(reason,status==='blocked'?'major':'good')}
function roadWorldEvents(){
 if(state.day===12)changeRoadWorld('store','hardware','blocked','商業區路面受熱變形，便利商店通往五金行的道路實際封閉；你未必已取得這項情報。');
 if(state.day===19)seedRoadRumor('warehouse','coldstore','danger','物流倉倖存者',62);
 if(state.day===23)changeRoadWorld('industrial','research','blocked','工業區通往研究園區的直達道路發生大面積路面破壞。');
 if(state.day===31)changeRoadWorld('fire','vent','blocked','永晝熱脹使消防站至中央通風站的主幹道局部崩塌。');
 if(state.day===42&&roadWorldState('store','hardware').status==='blocked')changeRoadWorld('store','hardware','open','其他倖存者清理了商業區舊阻塞，但你的舊情報不會自動更新。');
}
function dynamicEvents(){roadWorldEvents();if(state.day===8)log('夜晚縮短為 6 小時。','major');if(state.day===15)log('夜晚縮短為 4 小時。','major');if(state.day===22)log('夜晚只剩 2 小時。城市開始大規模囤積。','major');if(state.day===29)log('最後一夜。所有人都在搬運最後能搬的東西。','major');if(state.day===30){log('永晝開始。太陽不再落下，所有聚落重新評估避難位置。','major');state.phase='day';state.hoursLeft=0;if(!state.flags.v13Day30Seen){state.flags.v13Day30Seen=true;showDayTransition('DAY 30','永晝開始','太陽不再落下。從現在開始，安全區必須由你自己製造。')}}if(state.day===25)log('城市進入最後八夜的後半段：之後每一次漏掉的大型設備，Day 30 後搬運成本都會明顯上升。','major');if(state.day===34&&state.base.ventilation===0)log('中央站仍未啟動，基地冷卻壓力迅速升高。','bad');if(state.day===40&&state.coldStations.length===0)log('沒有外部冷站，你的永晝探索效率嚴重受限。','bad');if(state.day===45&&state.knownCore)log('冷源核心位置已確認，現在需要完成核心工程研究。','major');if(state.day===50&&!state.base.core)log(`距離 Day 60 只剩十天。核心工程目前 ${state.coreProject.stage}/10。`,'bad');if(state.day===55&&!state.base.core)log(`Day 55：核心工程 ${state.coreProject.stage}/10。若尚未進入吊裝後階段，城市級結局已非常吃緊。`,'bad')}

let audioEnabled=false,audioCtx=null;
function setBodyState(){
 document.body.classList.remove('phase-night','phase-day','phase-endless','risk-calm','risk-warn','risk-high','risk-critical','heat-shimmer');
 document.body.classList.add(state.day>=30?'phase-endless':state.phase==='night'?'phase-night':'phase-day');
 const score=currentRiskScore(); const rc=score>=9?'risk-critical':score>=6?'risk-high':score>=3?'risk-warn':'risk-calm';document.body.classList.add(rc);
 if(state.day>=30||state.phase==='day')document.body.classList.add('heat-shimmer');
}
